
export const allLocations = [
  { value: 'johannesburg', label: 'Johannesburg' },
  { value: 'sandton', label: 'Sandton' },
  { value: 'rosebank', label: 'Rosebank' },
  { value: 'fourways', label: 'Fourways' },
  { value: 'randburg', label: 'Randburg' },
  { value: 'midrand', label: 'Midrand' },
  { value: 'roodepoort', label: 'Roodepoort' },
  { value: 'bryanston', label: 'Bryanston' },
  { value: 'sunninghill', label: 'Sunninghill' },
  { value: 'bedfordview', label: 'Bedfordview' },
  { value: 'edenvale', label: 'Edenvale' },
  { value: 'soweto', label: 'Soweto' },
  { value: 'melville', label: 'Melville' },
  { value: 'parkhurst', label: 'Parkhurst' },
  { value: 'greenside', label: 'Greenside' },
  { value: 'northcliff', label: 'Northcliff' },
  { value: 'linden', label: 'Linden' },
  { value: 'emmarentia', label: 'Emmarentia' },
  { value: 'houghton-estate', label: 'Houghton Estate' },
  { value: 'craighall-park', label: 'Craighall Park' },
  { value: 'parktown-north', label: 'Parktown North' },
  { value: 'dunkeld', label: 'Dunkeld' },
  { value: 'hydepark', label: 'Hyde Park' },
  { value: 'morningside', label: 'Morningside' },
  { value: 'rivonia', label: 'Rivonia' },
  { value: 'lonehill', label: 'Lonehill' },
  { value: 'douglasdale', label: 'Douglasdale' },
  { value: 'kensington', label: 'Kensington' },
  { value: 'observatory', label: 'Observatory' },
  { value: 'cyrildene', label: 'Cyrildene' },
  { value: 'orange-grove', label: 'Orange Grove' },
  { value: 'norwood', label: 'Norwood' },
  { value: 'bassonia', label: 'Bassonia' },
  { value: 'glenvista', label: 'Glenvista' },
  { value: 'mulbarton', label: 'Mulbarton' },
  { value: 'alberton', label: 'Alberton' },
  { value: 'boksburg', label: 'Boksburg' },
  { value: 'benoni', label: 'Benoni' },
  { value: 'germiston', label: 'Germiston' },
  { value: 'kempton-park', label: 'Kempton Park' },
  { value: 'braamfontein', label: 'Braamfontein' },
  { value: 'auckland-park', label: 'Auckland Park' },
  { value: 'westdene', label: 'Westdene' },
  { value: 'ferndale', label: 'Ferndale' },
  { value: 'cresta', label: 'Cresta' },
  { value: 'fairland', label: 'Fairland' },
  { value: 'weltevredenpark', label: 'Weltevredenpark' },
  { value: 'constantia-kloof', label: 'Constantia Kloof' },
  { value: 'florida', label: 'Florida' },
  { value: 'cosmo-city', label: 'Cosmo City' },
  { value: 'zandspruit', label: 'Zandspruit' },
  { value: 'diepsloot', label: 'Diepsloot' },
  { value: 'alexandra', label: 'Alexandra' },
  { value: 'woodmead', label: 'Woodmead' },
  { value: 'kyalami', label: 'Kyalami' },
  { value: 'gallo-manor', label: 'Gallo Manor' },
  { value: 'paulshof', label: 'Paulshof' },
  { value: 'illovo', label: 'Illovo' },
  { value: 'parkmore', label: 'Parkmore' },
  { value: 'sandhurst', label: 'Sandhurst' },
  { value: 'inanda', label: 'Inanda' },
  { value: 'atholl', label: 'Atholl' },
  { value: 'melrose', label: 'Melrose' },
  { value: 'birdhaven', label: 'Birdhaven' },
  { value: 'killarney', label: 'Killarney' },
  { value: 'forest-town', label: 'Forest Town' },
  { value: 'westcliff', label: 'Westcliff' },
  { value: 'parkview', label: 'Parkview' },
  { value: 'victory-park', label: 'Victory Park' },
  { value: 'darrenwood', label: 'Darrenwood' },
  { value: 'robindale', label: 'Robindale' },
  { value: 'blairgowrie', label: 'Blairgowrie' },
  { value: 'pine-park', label: 'Pine Park' },
  { value: 'liefde-en-vrede', label: 'Liefde En Vrede' },
  { value: 'lindberg-park', label: 'Lindberg Park' },
  { value: 'linksfield', label: 'Linksfield' },
  { value: 'linksfield-north', label: 'Linksfield North' },
  { value: 'linksfield-ridge', label: 'Linksfield Ridge' },
  { value: 'linmeyer', label: 'Linmeyer' },
  { value: 'abbotsford', label: 'Abbotsford' },
  { value: 'alan-manor', label: 'Alan Manor' },
  { value: 'albertskroon', label: 'Albertskroon' },
  { value: 'albertville', label: 'Albertville' },
  { value: 'aspen-hills', label: 'Aspen Hills' },
  { value: 'beacon-royal', label: 'Beacon Royal' },
  { value: 'belgravia', label: 'Belgravia' },
  { value: 'bellavista-estate', label: 'Bellavista Estate' },
  { value: 'bellevue', label: 'Bellevue' },
  { value: 'bellevue-east', label: 'Bellevue East' },
  { value: 'benrose', label: 'Benrose' },
  { value: 'berario', label: 'Berario' },
  { value: 'berea', label: 'Berea' },
  { value: 'berea-north', label: 'Berea North' },
  { value: 'bertrams', label: 'Bertrams' },
  { value: 'bezuidenhout-valley', label: 'Bezuidenhout Valley' },
  { value: 'blackheath', label: 'Blackheath' },
  { value: 'blue-haven', label: 'Blue Haven' },
  { value: 'bordeaux', label: 'Bordeaux' },
  { value: 'bosmont', label: 'Bosmont' },
  { value: 'bramley', label: 'Bramley' },
  { value: 'bramley-view', label: 'Bramley View' },
  { value: 'brixton', label: 'Brixton' },
  { value: 'city-deep', label: 'City Deep' },
  { value: 'city-and-suburban', label: 'City and Suburban' },
  { value: 'corlett-gardens', label: 'Corlett Gardens' },
  { value: 'coronationville', label: 'Coronationville' },
  { value: 'crown-gardens', label: 'Crown Gardens' },
  { value: 'dewetshof', label: 'Dewetshof' },
  { value: 'doornfontein', label: 'Doornfontein' },
  { value: 'east-park', label: 'East Park' },
  { value: 'east-town', label: 'East Town' },
  { value: 'elton-hill', label: 'Elton Hill' },
  { value: 'ennerdale', label: 'Ennerdale' },
  { value: 'fairview', label: 'Fairview' },
  { value: 'ferraris', label: 'Ferraris' },
  { value: 'fietas', label: 'Fietas' },
  { value: 'forbesdale', label: 'Forbesdale' },
  { value: 'fordburg', label: 'Fordburg' },
  { value: 'forest-hill', label: 'Forest Hill' },
  { value: 'formain', label: 'Formain' },
  { value: 'framont', label: 'Framont' },
  { value: 'gillview', label: 'Gillview' },
  { value: 'glenhazel', label: 'Glenhazel' },
  { value: 'greymont', label: 'Greymont' },
  { value: 'haddon', label: 'Haddon' },
  { value: 'halfway-house', label: 'Halfway House' },
  { value: 'hawkins-estate', label: 'Hawkins Estate' },
  { value: 'highlands-north', label: 'Highlands North' },
  { value: 'hillbrow', label: 'Hillbrow' },
  { value: 'homestead-park', label: 'Homestead Park' },
  { value: 'hurst-hill', label: 'Hurst Hill' },
  { value: 'jeppestown', label: 'Jeppestown' },
  { value: 'johannesburg-north', label: 'Johannesburg North' },
  { value: 'johannesburg-south', label: 'Johannesburg South' },
  { value: 'judiths-paarl', label: 'Judith\'s Paarl' },
  { value: 'jukskei-park', label: 'Jukskei Park' },
  { value: 'kelvin', label: 'Kelvin' },
  { value: 'kenware', label: 'Kenware' },
  { value: 'kew', label: 'Kew' },
  { value: 'kibler-park', label: 'Kibler Park' },
  { value: 'kleve-hill-park', label: 'Kleve Hill Park' },
  { value: 'langlaagte', label: 'Langlaagte' },
  { value: 'la-rochelle', label: 'La Rochelle' },
  { value: 'lenasia', label: 'Lenasia' },
  { value: 'lorentzville', label: 'Lorentzville' },
  { value: 'malanshof', label: 'Malanshof' },
  { value: 'malvern', label: 'Malvern' },
  { value: 'marshalltown', label: 'Marshalltown' },
  { value: 'maryvale', label: 'Maryvale' },
  { value: 'mayfair', label: 'Mayfair' },
  { value: 'melrose-arch', label: 'Melrose Arch' },
  { value: 'melrose-estate', label: 'Melrose Estate' },
  { value: 'melrose-north', label: 'Melrose North' },
  { value: 'mondeor', label: 'Mondeor' },
  { value: 'montgomery-park', label: 'Montgomery Park' },
  { value: 'mountain-view', label: 'Mountain View' },
  { value: 'naturena', label: 'Naturena' },
  { value: 'newcentre', label: 'Newcentre' },
  { value: 'newclare', label: 'Newclare' },
  { value: 'newlands', label: 'Newlands' },
  { value: 'newtown', label: 'Newtown' },
  { value: 'northdene', label: 'Northdene' },
  { value: 'northgate', label: 'Northgate' },
  { value: 'northwood', label: 'Northwood' },
  { value: 'oakdene', label: 'Oakdene' },
  { value: 'ophirton', label: 'Ophirton' },
  { value: 'orchards', label: 'Orchards' },
  { value: 'orlando', label: 'Orlando' },
  { value: 'pageview', label: 'Pageview' },
  { value: 'parktown', label: 'Parktown' },
  { value: 'percelia-estate', label: 'Percelia Estate' },
  { value: 'president-ridge', label: 'President Ridge' },
  { value: 'quellerina', label: 'Quellerina' },
  { value: 'raedene-estate', label: 'Raedene Estate' },
  { value: 'randpark', label: 'Randpark' },
  { value: 'randpark-ridge', label: 'Randpark Ridge' },
  { value: 'ranview', label: 'Ranview' },
  { value: 'rembrandt-park', label: 'Rembrandt Park' },
  { value: 'rewlatch', label: 'Rewlatch' },
  { value: 'reynolds-view', label: 'Reynolds View' },
  { value: 'richmond', label: 'Richmond' },
  { value: 'ridgeway', label: 'Ridgeway' },
  { value: 'risana', label: 'Risana' },
  { value: 'risidale', label: 'Risidale' },
  { value: 'riverlea', label: 'Riverlea' },
  { value: 'robertsham', label: 'Robertsham' },
  { value: 'robin-hills', label: 'Robin Hills' },
  { value: 'rooseveldt-park', label: 'Rooseveldt Park' },
  { value: 'rosettenville', label: 'Rosettenville' },
  { value: 'rouxville', label: 'Rouxville' },
  { value: 'sandown', label: 'Sandown' },
  { value: 'savoy-estate', label: 'Savoy Estate' },
  { value: 'saxonwold', label: 'Saxonwold' },
  { value: 'selby', label: 'Selby' },
  { value: 'selwyn', label: 'Selwyn' },
  { value: 'southdale', label: 'Southdale' },
  { value: 'south-hills', label: 'South Hills' },
  { value: 'spruitview', label: 'Spruitview' },
  { value: 'steeledale', label: 'Steeledale' },
  { value: 'sunnyside', label: 'Sunnyside' },
  { value: 'thembelihle', label: 'Thembelihle' },
  { value: 'theta', label: 'Theta' },
  { value: 'towerby', label: 'Towerby' },
  { value: 'troyeville', label: 'Troyeville' },
  { value: 'turf-club', label: 'Turf Club' },
  { value: 'turffontein', label: 'Turffontein' },
  { value: 'unigray', label: 'Unigray' },
  { value: 'vrededorp', label: 'Vrededorp' },
  { value: 'viewcrest', label: 'Viewcrest' },
  { value: 'village-main', label: 'Village Main' },
  { value: 'wanderers', label: 'Wanderers' },
  { value: 'waverley', label: 'Waverley' },
  { value: 'westgate', label: 'Westgate' },
  { value: 'whitney-gardens', label: 'Whitney Gardens' },
  { value: 'wilro-park', label: 'Wilro Park' },
  { value: 'windsor', label: 'Windsor' },
  { value: 'windy-brow', label: 'Windy Brow' },
  { value: 'winston-ridge', label: 'Winston Ridge' },
  { value: 'wolhuter', label: 'Wolhuter' },
  { value: 'yeoville', label: 'Yeoville' },
  { value: 'zevenfontein', label: 'Zevenfontein' },
  { value: 'akasia', label: 'Akasia' },
  { value: 'atteridgeville', label: 'Atteridgeville' },
  { value: 'brakpan', label: 'Brakpan' },
  { value: 'bronkhorstspruit', label: 'Bronkhorstspruit' },
  { value: 'carletonville', label: 'Carletonville' },
  { value: 'centurion', label: 'Centurion' },
  { value: 'annlin', label: 'Annlin' },
  { value: 'arcadia', label: 'Arcadia' },
  { value: 'ashlea-gardens', label: 'Ashlea Gardens' },
  { value: 'brooklyn', label: 'Brooklyn' },
  { value: 'colbyn', label: 'Colbyn' },
  { value: 'constantia-park', label: 'Constantia Park' },
  { value: 'die-wilgers', label: 'Die Wilgers' },
  { value: 'erasmuskloof', label: 'Erasmuskloof' },
  { value: 'erasmusrand', label: 'Erasmusrand' },
  { value: 'faerie-glen', label: 'Faerie Glen' },
  { value: 'gezina', label: 'Gezina' },
  { value: 'groenkloof', label: 'Groenkloof' },
  { value: 'hatfield', label: 'Hatfield' },
  { value: 'hazelwood', label: 'Hazelwood' },
  { value: 'lynnwood', label: 'Lynnwood' },
  { value: 'menlo-park', label: 'Menlo Park' },
  { value: 'menlyn', label: 'Menlyn' },
  { value: 'monument-park', label: 'Monument Park' },
  { value: 'mooikloof', label: 'Mooikloof' },
  { value: 'moreleta-park', label: 'Moreleta Park' },
  { value: 'muckleneuk', label: 'Muckleneuk' },
  { value: 'newlands-pta', label: 'Newlands' },
  { value: 'olympus', label: 'Olympus' },
  { value: 'pretoria-east', label: 'Pretoria East' },
  { value: 'pretoria-north', label: 'Pretoria North' },
  { value: 'pretoria-west', label: 'Pretoria West' },
  { value: 'queenswood', label: 'Queenswood' },
  { value: 'rietfontein', label: 'Rietfontein' },
  { value: 'silver-lakes', label: 'Silver Lakes' },
  { value: 'sinoville', label: 'Sinoville' },
  { value: 'waterkloof', label: 'Waterkloof' },
  { value: 'willow-glen', label: 'Willow Glen' },
  { value: 'wonderboom', label: 'Wonderboom' },
  { value: 'albertinia', label: 'Albertinia' },
  { value: 'ashton', label: 'Ashton' },
  { value: 'atlantis', label: 'Atlantis' },
  { value: 'beaufort-west', label: 'Beaufort West' },
  { value: 'belhar', label: 'Belhar' },
  { value: 'bellville', label: 'Bellville' },
  { value: 'bettys-bay', label: 'Bettys Bay' },
  { value: 'big-bay', label: 'Big Bay' },
  { value: 'blackheath', label: 'Blackheath' },
  { value: 'blouberg', label: 'Blouberg' },
  { value: 'athlone', label: 'Athlone' },
  { value: 'bakoven', label: 'Bakoven' },
  { value: 'bantry-bay', label: 'Bantry Bay' },
  { value: 'bishop-lavis', label: 'Bishop Lavis' },
  { value: 'bishopscourt', label: 'Bishopscourt' },
  { value: 'bonteheuwel', label: 'Bonteheuwel' },
  { value: 'brackenfell', label: 'Brackenfell' },
  { value: 'camps-bay', label: 'Camps Bay' },
  { value: 'claremont', label: 'Claremont' },
  { value: 'clifton', label: 'Clifton' },
  { value: 'constantia', label: 'Constantia' },
  { value: 'diep-river', label: 'Diep River' },
  { value: 'elsies-river', label: 'Elsies River' },
  { value: 'fish-hoek', label: 'Fish Hoek' },
  { value: 'fresnaye', label: 'Fresnaye' },
  { value: 'gardens', label: 'Gardens' },
  { value: 'green-point', label: 'Green Point' },
  { value: 'gugulethu', label: 'Gugulethu' },
  { value: 'handover-park', label: 'Handover Park' },
  { value: 'harfield-village', label: 'Harfield Village' },
  { value: 'hazyview', label: 'Hazyview' },
  { value: 'hout-bay', label: 'Hout Bay' },
  { value: 'kenilworth', label: 'Kenilworth' },
  { value: 'khayelitsha', label: 'Khayelitsha' },
  { value: 'kommetjie', label: 'Kommetjie' },
  { value: 'lakeside', label: 'Lakeside' },
  { value: 'llandudno', label: 'Llandudno' },
  { value: 'maitland', label: 'Maitland' },
  { value: 'mouille-point', label: 'Mouille Point' },
  { value: 'mowbray', label: 'Mowbray' },
  { value: 'muizenberg', label: 'Muizenberg' },
  { value: 'newlands-ct', label: 'Newlands' },
  { value: 'nyanga', label: 'Nyanga' },
  { value: 'observatory-ct', label: 'Observatory' },
  { value: 'oranjezicht', label: 'Oranjezicht' },
  { value: 'ottery', label: 'Ottery' },
  { value: 'parow', label: 'Parow' },
  { value: 'pinelands', label: 'Pinelands' },
  { value: 'plumstead', label: 'Plumstead' },
  { value: 'retreat', label: 'Retreat' },
  { value: 'rondebosch', label: 'Rondebosch' },
  { value: 'sea-point', label: 'Sea Point' },
  { value: 'simons-town', label: 'Simons Town' },
  { value: 'southfield', label: 'Southfield' },
  { value: 'tamboerskloof', label: 'Tamboerskloof' },
  { value: 'vredehoek', label: 'Vredehoek' },
  { value: 'walmer-estate', label: 'Walmer Estate' },
  { value: 'woodstock', label: 'Woodstock' },
  { value: 'wynberg', label: 'Wynberg' },
  { value: 'amanzimtoti', label: 'Amanzimtoti' },
  { value: 'anerley', label: 'Anerley' },
  { value: 'ashburton', label: 'Ashburton' },
  { value: 'ballito', label: 'Ballito' },
  { value: 'berea-dbn', label: 'Berea' },
  { value: 'bergville', label: 'Bergville' },
  { value: 'blackburn', label: 'Blackburn' },
  { value: 'bluff', label: 'Bluff' },
  { value: 'camperdown', label: 'Camperdown' },
  { value: 'cato-ridge', label: 'Cato Ridge' },
  { value: 'aliwal-north', label: 'Aliwal North' },
  { value: 'bizana', label: 'Bizana' },
  { value: 'butterworth', label: 'Butterworth' },
  { value: 'despatch', label: 'Despatch' },
  { value: 'east-london', label: 'East London' },
  { value: 'gonubie', label: 'Gonubie' },
  { value: 'graaff-reinet', label: 'Graaff-Reinet' },
  { value: 'grahamstown', label: 'Grahamstown' },
  { value: 'humansdorp', label: 'Humansdorp' },
  { value: 'jeffreys-bay', label: 'Jeffreys Bay' },
  { value: 'bethlehem', label: 'Bethlehem' },
  { value: 'bloemfontein', label: 'Bloemfontein' },
  { value: 'bothaville', label: 'Bothaville' },
  { value: 'clarens', label: 'Clarens' },
  { value: 'deneysville', label: 'Deneysville' },
  { value: 'ficksburg', label: 'Ficksburg' },
  { value: 'frankfort', label: 'Frankfort' },
  { value: 'harrismith', label: 'Harrismith' },
  { value: 'heilbron', label: 'Heilbron' },
  { value: 'kroonstad', label: 'Kroonstad' },
  { value: 'bela-bela', label: 'Bela-Bela' },
  { value: 'bochum', label: 'Bochum' },
  { value: 'burgersfort', label: 'Burgersfort' },
  { value: 'giyani', label: 'Giyani' },
  { value: 'groblersdal', label: 'Groblersdal' },
  { value: 'hoedspruit', label: 'Hoedspruit' },
  { value: 'lephalale', label: 'Lephalale' },
  { value: 'louis-trichardt', label: 'Louis Trichardt' },
  { value: 'malamulele', label: 'Malamulele' },
  { value: 'marble-hall', label: 'Marble Hall' },
  { value: 'barberton', label: 'Barberton' },
  { value: 'bethal', label: 'Bethal' },
  { value: 'bushbuckridge', label: 'Bushbuckridge' },
  { value: 'delmas', label: 'Delmas' },
  { value: 'embalenhle', label: 'Embalenhle' },
  { value: 'ermelo', label: 'Ermelo' },
  { value: 'evander', label: 'Evander' },
  { value: 'hazyview-mp', label: 'Hazyview' },
  { value: 'komatipoort', label: 'Komatipoort' },
  { value: 'kriel', label: 'Kriel' },
  { value: 'brits', label: 'Brits' },
  { value: 'delareyville', label: 'Delareyville' },
  { value: 'hartbeespoort', label: 'Hartbeespoort' },
  { value: 'klerksdorp', label: 'Klerksdorp' },
  { value: 'koster', label: 'Koster' },
  { value: 'lichtenburg', label: 'Lichtenburg' },
  { value: 'mahikeng', label: 'Mahikeng' },
  { value: 'marikana', label: 'Marikana' },
  { value: 'mmabatho', label: 'Mmabatho' },
  { value: 'orkney', label: 'Orkney' },
  { value: 'barkly-west', label: 'Barkly West' },
  { value: 'colesberg', label: 'Colesberg' },
  { value: 'danielskuil', label: 'Danielskuil' },
  { value: 'de-aar', label: 'De Aar' },
  { value: 'hartswater', label: 'Hartswater' },
  { value: 'jan-kempdorp', label: 'Jan Kempdorp' },
  { value: 'kakamas', label: 'Kakamas' },
  { value: 'kathu', label: 'Kathu' },
  { value: 'keimoes', label: 'Keimoes' },
  { value: 'kimberley', label: 'Kimberley' },
  { value: 'durban', label: 'Durban'},
  { value: 'cape-town', label: 'Cape Town'},
  { value: 'pretoria', label: 'Pretoria'},
];
