
export const cityExpansionMap: Record<string, string[]> = {
  johannesburg: [
    'johannesburg', 'sandton', 'randburg', 'roodepoort', 'midrand', 'soweto', 
    'alberton', 'boksburg', 'benoni', 'germiston', 'kempton-park', 'edenvale', 
    'bryanston', 'fourways', 'rosebank', 'vereeniging', 'vanderbijlpark', 
    'meyerton', 'sunninghill', 'melville', 'parkhurst', 'greenside', 'northcliff', 
    'linden', 'emmarentia', 'houghton-estate', 'craighall-park', 'parktown-north', 
    'dunkeld', 'hydepark', 'morningside', 'rivonia', 'lonehill', 'douglasdale', 
    'kensington', 'observatory', 'cyrildene', 'orange-grove', 'norwood', 
    'bassonia', 'glenvista', 'mulbarton', 'braamfontein', 'auckland-park', 
    'westdene', 'ferndale', 'cresta', 'fairland', 'weltevredenpark', 
    'constantia-kloof', 'florida', 'cosmo-city', 'zandspruit', 'diepsloot', 
    'alexandra', 'woodmead', 'kyalami', 'gallo-manor', 'paulshof', 'illovo', 
    'parkmore', 'sandhurst', 'inanda', 'atholl', 'melrose', 'birdhaven', 
    'killarney', 'forest-town', 'westcliff', 'parkview', 'victory-park', 
    'darrenwood', 'robindale', 'blairgowrie', 'pine-park', 'liefde-en-vrede', 
    'lindberg-park', 'linksfield', 'linksfield-north', 'linksfield-ridge', 'linmeyer',
    'abbotsford', 'alan-manor', 'albertskroon', 'albertville', 'aspen-hills',
    'beacon-royal', 'belgravia', 'bellavista-estate', 'bellevue', 'bellevue-east',
    'benrose', 'berario', 'berea', 'berea-north', 'bertrams', 'bezuidenhout-valley',
    'blackheath', 'blue-haven', 'bordeaux', 'bosmont', 'bramley', 'bramley-view', 'brixton',
    'city-deep', 'city-and-suburban', 'corlett-gardens', 'coronationville',
    'crown-gardens', 'dewetshof', 'doornfontein', 'east-park', 'east-town', 'elton-hill',
    'ennerdale', 'fairview', 'ferraris', 'fietas', 'forbesdale', 'fordburg', 'forest-hill',
    'formain', 'framont', 'gillview', 'glenhazel', 'greymont', 'haddon', 'halfway-house',
    'hawkins-estate', 'highlands-north', 'hillbrow', 'homestead-park', 'hurst-hill',
    'jeppestown', 'johannesburg-north', 'johannesburg-south', 'judiths-paarl', 'jukskei-park',
    'kelvin', 'kenware', 'kew', 'kibler-park', 'kleve-hill-park', 'langlaagte', 'la-rochelle',
    'lenasia', 'lorentzville', 'malanshof', 'malvern', 'marshalltown', 'maryvale', 'mayfair',
    'melrose-arch', 'melrose-estate', 'melrose-north', 'mondeor', 'montgomery-park',
    'mountain-view', 'naturena', 'newcentre', 'newclare', 'newlands', 'newtown', 'northdene',
    'northgate', 'northwood', 'oakdene', 'ophirton', 'orchards', 'orlando', 'pageview',
    'parktown', 'percelia-estate', 'president-ridge', 'quellerina', 'raedene-estate',
    'randpark', 'randpark-ridge', 'ranview', 'rembrandt-park', 'rewlatch', 'reynolds-view',
    'richmond', 'ridgeway', 'risana', 'risidale', 'riverlea', 'robertsham', 'robin-hills',
    'rooseveldt-park', 'rosettenville', 'rouxville', 'sandown', 'savoy-estate', 'saxonwold',
    'selby', 'selwyn', 'southdale', 'south-hills', 'spruitview', 'steeledale', 'sunnyside',
    'thembelihle', 'theta', 'towerby', 'troyeville', 'turf-club', 'turffontein', 'unigray',
    'vrededorp', 'viewcrest', 'village-main', 'wanderers', 'waverley', 'westgate',
    'whitney-gardens', 'wilro-park', 'windsor', 'windy-brow', 'winston-ridge', 'wolhuter', 'yeoville', 'zevenfontein'
  ],
  pretoria: [
    'pretoria', 'centurion', 'akasia', 'bronkhorstspruit', 'tembisa', 'midrand', 'atteridgeville',
    'annlin', 'arcadia', 'ashlea-gardens', 'brooklyn', 'colbyn', 'constantia-park', 'die-wilgers', 
    'erasmuskloof', 'erasmusrand', 'faerie-glen', 'gezina', 'groenkloof', 'hatfield', 'hazelwood', 
    'lynnwood', 'menlo-park', 'menlyn', 'monument-park', 'mooikloof', 'moreleta-park', 'muckleneuk', 
    'newlands-pta', 'olympus', 'pretoria-east', 'pretoria-north', 'pretoria-west', 'queenswood', 
    'rietfontein', 'silver-lakes', 'sinoville', 'waterkloof', 'willow-glen', 'wonderboom'
  ],
  'cape-town': [
    'cape-town', 'bellville', 'durbanville', 'mitchells-plain', 'goodwood', 
    'blackheath', 'atlantis', 'kraaifontein', 'kuils-river', 'table-view', 
    'stellenbosch', 'paarl', 'somerset-west', 'albertinia', 'ashton', 
    'beaufort-west', 'belhar', 'bettys-bay', 'big-bay', 'blouberg',
    'athlone', 'bakoven', 'bantry-bay', 'bishop-lavis', 'bishopscourt', 'bonteheuwel', 
    'brackenfell', 'camps-bay', 'claremont', 'clifton', 'constantia', 'diep-river', 
    'elsies-river', 'fish-hoek', 'fresnaye', 'gardens', 'green-point', 'gugulethu', 
    'handover-park', 'harfield-village', 'hazyview', 'hout-bay', 'kenilworth', 
    'khayelitsha', 'kommetjie', 'lakeside', 'llandudno', 'maitland', 'mouille-point', 
    'mowbray', 'muizenberg', 'newlands-ct', 'nyanga', 'observatory-ct', 'oranjezicht', 
    'ottery', 'parow', 'pinelands', 'plumstead', 'retreat', 'rondebosch', 'sea-point', 
    'simons-town', 'southfield', 'tamboerskloof', 'vredehoek', 'walmer-estate', 'woodstock', 'wynberg'
  ],
  durban: [
    'durban', 'amanzimtoti', 'ballito', 'chatsworth', 'hillcrest', 'kloof', 
    'phoenix', 'pinetown', 'umhlanga', 'umlazi', 'anerley', 'ashburton', 
    'bergville', 'blackburn', 'bluff', 'camperdown', 'cato-ridge'
  ],
  'port-elizabeth': ['port-elizabeth', 'despatch', 'humansdorp', 'jeffreys-bay'],
  'east-london': ['east-london', 'gonubie', 'aliwal-north', 'bizana', 'butterworth'],
  bloemfontein: ['bloemfontein', 'bethlehem', 'bothaville', 'clarens', 'deneysville', 'ficksburg', 'frankfort', 'harrismith', 'heilbron', 'kroonstad'],
  klerksdorp: ['klerksdorp', 'orkney', 'brits', 'delareyville', 'hartbeespoort', 'koster', 'lichtenburg', 'mahikeng', 'marikana', 'mmabatho'],
  rustenburg: ['rustenburg', 'marikana'],
  nelspruit: ['nelspruit', 'barberton', 'bethal', 'bushbuckridge', 'delmas', 'ermelo', 'evander', 'hazyview', 'komatipoort'],
  witbank: ['witbank', 'embalenhle', 'kriel'],
  polokwane: ['polokwane', 'bela-bela', 'bochum', 'burgersfort', 'giyani', 'groblersdal', 'hoedspruit', 'lephalale', 'louis-trichardt', 'malamulele', 'marble-hall'],
};
