
export const allLocations = [
  { value: 'johannesburg', label: 'Johannesburg' },
  { value: 'sandton', label: 'Sandton' },
  { value: 'rosebank', label: 'Rosebank' },
  { value: 'fourways', label: 'Fourways' },
  { value: 'randburg', label: 'Randburg' },
  { value: 'midrand', label: 'Midrand' },
  { value: 'roodepoort', label: 'Roodepoort' },
  { value: 'bryanston', label: 'Bryanston' },
  { value: 'sunninghill', label: 'Sunninghill' },
  { value: 'bedfordview', label: 'Bedfordview' },
  { value: 'edenvale', label: 'Edenvale' },
  { value: 'soweto', label: 'Soweto' },
  { value: 'melville', label: 'Melville' },
  { value: 'parkhurst', label: 'Parkhurst' },
  { value: 'greenside', label: 'Greenside' },
  { value: 'northcliff', label: 'Northcliff' },
  { value: 'linden', label: 'Linden' },
  { value: 'emmarentia', label: 'Emmarentia' },
  { value: 'houghton-estate', label: 'Houghton Estate' },
  { value: 'craighall-park', label: 'Craighall Park' },
  { value: 'parktown-north', label: 'Parktown North' },
  { value: 'dunkeld', label: 'Dunkeld' },
  { value: 'hydepark', label: 'Hyde Park' },
  { value: 'morningside', label: 'Morningside' },
  { value: 'rivonia', label: 'Rivonia' },
  { value: 'lonehill', label: 'Lonehill' },
  { value: 'douglasdale', label: 'Douglasdale' },
  { value: 'kensington', label: 'Kensington' },
  { value: 'observatory', label: 'Observatory' },
  { value: 'cyrildene', label: 'Cyrildene' },
  { value: 'orange-grove', label: 'Orange Grove' },
  { value: 'norwood', label: 'Norwood' },
  { value: 'bassonia', label: 'Bassonia' },
  { value: 'glenvista', label: 'Glenvista' },
  { value: 'mulbarton', label: 'Mulbarton' },
  { value: 'alberton', label: 'Alberton' },
  { value: 'boksburg', label: 'Boksburg' },
  { value: 'benoni', label: 'Benoni' },
  { value: 'germiston', label: 'Germiston' },
  { value: 'kempton-park', label: 'Kempton Park' },
  { value: 'braamfontein', label: 'Braamfontein' },
  { value: 'auckland-park', label: 'Auckland Park' },
  { value: 'westdene', label: 'Westdene' },
  { value: 'ferndale', label: 'Ferndale' },
  { value: 'cresta', label: 'Cresta' },
  { value: 'fairland', label: 'Fairland' },
  { value: 'weltevredenpark', label: 'Weltevredenpark' },
  { value: 'constantia-kloof', label: 'Constantia Kloof' },
  { value: 'florida', label: 'Florida' },
  { value: 'cosmo-city', label: 'Cosmo City' },
  { value: 'zandspruit', label: 'Zandspruit' },
  { value: 'diepsloot', label: 'Diepsloot' },
  { value: 'alexandra', label: 'Alexandra' },
  { value: 'woodmead', label: 'Woodmead' },
  { value: 'kyalami', label: 'Kyalami' },
  { value: 'gallo-manor', label: 'Gallo Manor' },
  { value: 'paulshof', label: 'Paulshof' },
  { value: 'illovo', label: 'Illovo' },
  { value: 'parkmore', label: 'Parkmore' },
  { value: 'sandhurst', label: 'Sandhurst' },
  { value: 'inanda', label: 'Inanda' },
  { value: 'atholl', label: 'Atholl' },
  { value: 'melrose', label: 'Melrose' },
  { value: 'birdhaven', label: 'Birdhaven' },
  { value: 'killarney', label: 'Killarney' },
  { value: 'forest-town', label: 'Forest Town' },
  { value: 'westcliff', label: 'Westcliff' },
  { value: 'parkview', label: 'Parkview' },
  { value: 'victory-park', label: 'Victory Park' },
  { value: 'darrenwood', label: 'Darrenwood' },
  { value: 'robindale', label: 'Robindale' },
  { value: 'blairgowrie', label: 'Blairgowrie' },
  { value: 'pine-park', label: 'Pine Park' },
  { value: 'akasia', label: 'Akasia' },
  { value: 'atteridgeville', label: 'Atteridgeville' },
  { value: 'brakpan', label: 'Brakpan' },
  { value: 'bronkhorstspruit', label: 'Bronkhorstspruit' },
  { value: 'carletonville', label: 'Carletonville' },
  { value: 'centurion', label: 'Centurion' },
  { value: 'albertinia', label: 'Albertinia' },
  { value: 'ashton', label: 'Ashton' },
  { value: 'atlantis', label: 'Atlantis' },
  { value: 'beaufort-west', label: 'Beaufort West' },
  { value: 'belhar', label: 'Belhar' },
  { value: 'bellville', label: 'Bellville' },
  { value: 'bettys-bay', label: 'Bettys Bay' },
  { value: 'big-bay', label: 'Big Bay' },
  { value: 'blackheath', label: 'Blackheath' },
  { value: 'blouberg', label: 'Blouberg' },
  { value: 'amanzimtoti', label: 'Amanzimtoti' },
  { value: 'anerley', label: 'Anerley' },
  { value: 'ashburton', label: 'Ashburton' },
  { value: 'ballito', label: 'Ballito' },
  { value: 'berea', label: 'Berea' },
  { value: 'bergville', label: 'Bergville' },
  { value: 'blackburn', label: 'Blackburn' },
  { value: 'bluff', label: 'Bluff' },
  { value: 'camperdown', label: 'Camperdown' },
  { value: 'cato-ridge', label: 'Cato Ridge' },
  { value: 'aliwal-north', label: 'Aliwal North' },
  { value: 'bizana', label: 'Bizana' },
  { value: 'butterworth', label: 'Butterworth' },
  { value: 'despatch', label: 'Despatch' },
  { value: 'east-london', label: 'East London' },
  { value: 'gonubie', label: 'Gonubie' },
  { value: 'graaff-reinet', label: 'Graaff-Reinet' },
  { value: 'grahamstown', label: 'Grahamstown' },
  { value: 'humansdorp', label: 'Humansdorp' },
  { value: 'jeffreys-bay', label: 'Jeffreys Bay' },
  { value: 'bethlehem', label: 'Bethlehem' },
  { value: 'bloemfontein', label: 'Bloemfontein' },
  { value: 'bothaville', label: 'Bothaville' },
  { value: 'clarens', label: 'Clarens' },
  { value: 'deneysville', label: 'Deneysville' },
  { value: 'ficksburg', label: 'Ficksburg' },
  { value: 'frankfort', label: 'Frankfort' },
  { value: 'harrismith', label: 'Harrismith' },
  { value: 'heilbron', label: 'Heilbron' },
  { value: 'kroonstad', label: 'Kroonstad' },
  { value: 'bela-bela', label: 'Bela-Bela' },
  { value: 'bochum', label: 'Bochum' },
  { value: 'burgersfort', label: 'Burgersfort' },
  { value: 'giyani', label: 'Giyani' },
  { value: 'groblersdal', label: 'Groblersdal' },
  { value: 'hoedspruit', label: 'Hoedspruit' },
  { value: 'lephalale', label: 'Lephalale' },
  { value: 'louis-trichardt', label: 'Louis Trichardt' },
  { value: 'malamulele', label: 'Malamulele' },
  { value: 'marble-hall', label: 'Marble Hall' },
  { value: 'barberton', label: 'Barberton' },
  { value: 'bethal', label: 'Bethal' },
  { value: 'bushbuckridge', label: 'Bushbuckridge' },
  { value: 'delmas', label: 'Delmas' },
  { value: 'embalenhle', label: 'Embalenhle' },
  { value: 'ermelo', label: 'Ermelo' },
  { value: 'evander', label: 'Evander' },
  { value: 'hazyview', label: 'Hazyview' },
  { value: 'komatipoort', label: 'Komatipoort' },
  { value: 'kriel', label: 'Kriel' },
  { value: 'brits', label: 'Brits' },
  { value: 'delareyville', label: 'Delareyville' },
  { value: 'hartbeespoort', label: 'Hartbeespoort' },
  { value: 'klerksdorp', label: 'Klerksdorp' },
  { value: 'koster', label: 'Koster' },
  { value: 'lichtenburg', label: 'Lichtenburg' },
  { value: 'mahikeng', label: 'Mahikeng' },
  { value: 'marikana', label: 'Marikana' },
  { value: 'mmabatho', label: 'Mmabatho' },
  { value: 'orkney', label: 'Orkney' },
  { value: 'barkly-west', label: 'Barkly West' },
  { value: 'colesberg', label: 'Colesberg' },
  { value: 'danielskuil', label: 'Danielskuil' },
  { value: 'de-aar', label: 'De Aar' },
  { value: 'hartswater', label: 'Hartswater' },
  { value: 'jan-kempdorp', label: 'Jan Kempdorp' },
  { value: 'kakamas', label: 'Kakamas' },
  { value: 'kathu', label: 'Kathu' },
  { value: 'keimoes', label: 'Keimoes' },
  { value: 'kimberley', label: 'Kimberley' },
  { value: 'durban', label: 'Durban'},
  { value: 'cape-town', label: 'Cape Town'},
  { value: 'pretoria', label: 'Pretoria'},
];
    