
export const allProfessionals = {
    "fire-safety": [
        {
            id: "fire-safe-solutions-jhb",
            name: "Fire-Safe Solutions JHB",
            location: "Johannesburg",
            description: "Suppliers and service agents for all fire safety equipment. We provide fire extinguisher servicing, fire detection system installation, and fire safety compliance certificates for businesses.",
            rating: 4.8,
            reviews: 14,
            isProVerified: true,
            yearsInBusiness: 12,
            employees: 15,
            businessHours: "Mon-Fri, 8am-5pm",
            tags: ["Fire Extinguishers", "Fire Detection", "Compliance Certificates"],
            reviewData: [
                { author: "Office Parks Inc.", rating: 5, comment: "They handle the annual fire safety compliance for all our buildings. Very professional and reliable service." },
                { author: "J. Smit", rating: 4, comment: "Good service for our extinguisher maintenance. On time and efficient." },
                { author: "Retail Store", rating: 5, comment: "Helped us get our fire certificate sorted out quickly before our inspection." },
                { author: "Thabo M.", rating: 5, comment: "The technician was knowledgeable and explained everything clearly." },
                { author: "Anna V.", rating: 4, comment: "Good service, though scheduling took a few tries." },
                { author: "Complex Manager", rating: 5, comment: "They installed a new detection system for our complex. The installation was neat and professional." },
                { author: "Factory Safety", rating: 5, comment: "Reliable and professional. They keep our factory compliant and safe." },
                { author: "Sarah L.", rating: 5, comment: "Quick response and great service when we needed an urgent replacement." },
                { author: "Mike B.", rating: 4, comment: "Their pricing is fair and the work is solid." },
                { author: "Restaurant Owner", rating: 5, comment: "They come every year to service our kitchen extinguishers. Never had an issue." },
                { author: "Priya N.", rating: 5, comment: "Very helpful team. Made the compliance process easy to understand." },
                { author: "David Chen", rating: 5, comment: "Professional, efficient, and thorough. I trust them with our safety." },
                { author: "Building Admin", rating: 4, comment: "Consistent service over the years. Recommended." },
                { author: "Safety Officer", rating: 5, comment: "Excellent knowledge of fire safety regulations." }
            ],
            photos: ["https://picsum.photos/seed/firesafety1/600/400"],
            avatarSeed: "fire-safe-solutions-logo"
        },
        {
            id: "national-fire-protection",
            name: "National Fire Protection",
            location: "Nationwide",
            description: "A leading provider of fire protection services, including the installation and maintenance of sprinkler systems, fire alarms, and emergency evacuation planning for large commercial and industrial sites.",
            rating: 4.7,
            reviews: 15,
            isProVerified: true,
            yearsInBusiness: 25,
            employees: 200,
            businessHours: "Open 24/7",
            tags: ["Sprinkler Systems", "Fire Alarms", "Evacuation Planning"],
            reviewData: [
                { author: "Mega Malls Pty", rating: 5, comment: "Their expertise in large-scale fire suppression systems is unmatched. A crucial partner for our facilities." },
                { author: "Industrial Park", rating: 5, comment: "The best in the business for industrial fire safety. Their systems are top-tier." },
                { author: "Data Center", rating: 5, comment: "Installed a clean agent fire suppression system for us. Highly specialized and professional." },
                { author: "Logistics Hub", rating: 4, comment: "A huge project that was managed well. A few minor delays but the end result is excellent." },
                { author: "Hospital Group", rating: 5, comment: "Their knowledge of healthcare facility fire codes is impressive. They ensure we are always compliant." },
                { author: "Aviation Co", rating: 5, comment: "Handled the fire safety for our hangars. Very specialized work done perfectly." },
                { author: "PetroChem Plant", rating: 4, comment: "Complex industrial environment, and they handled it with expertise." },
                { author: "National Retailer", rating: 5, comment: "We use them for all our new stores nationwide. Consistent and reliable." },
                { author: "Mining Operation", rating: 5, comment: "Their systems are robust and built for tough environments. Excellent service." },
                { author: "Consulting Engineer", rating: 5, comment: "I recommend them to all my clients for large-scale projects. They are true experts." },
                { author: "Property Group", rating: 4, comment: "Good service and maintenance contracts for our entire portfolio." },
                { author: "J. Botha", rating: 5, comment: "The level of detail in their planning is exceptional." },
                { author: "Safety Consultant", rating: 5, comment: "They are my go-to for technical fire safety systems. Always up-to-date with the latest tech." },
                { author: "S. Williams", rating: 4, comment: "The project was complex but they delivered. Happy with the result." },
                { author: "International Airport", rating: 5, comment: "Their work is of an international standard. Highly recommended for critical infrastructure." }
            ],
            photos: ["https://picsum.photos/seed/firesafety2/600/400", "https://picsum.photos/seed/firesafety3/600/400"],
            avatarSeed: "national-fire-logo"
        },
        {
            id: "cape-fire-compliance",
            name: "Cape Fire & Compliance",
            location: "Cape Town, Western Cape",
            description: "Helping businesses in the Western Cape stay compliant with fire safety regulations. We offer fire risk assessments, fire extinguisher servicing, and staff training.",
            rating: 4.9,
            reviews: 12,
            isProVerified: true,
            yearsInBusiness: 8,
            employees: 10,
            businessHours: "Mon-Fri, 9am-5pm",
            tags: ["Risk Assessments", "Fire Extinguisher Servicing", "Staff Training"],
            reviewData: [
                { author: "The Eatery Group", rating: 5, comment: "Made the process of getting our restaurant compliant very easy. The inspector was knowledgeable and helpful." },
                { author: "Boutique Hotel", rating: 5, comment: "Excellent service. They are thorough and very professional. Peace of mind for our business." },
                { author: "Wine Farm", rating: 5, comment: "Helped us navigate the specific fire risks associated with our production facility. Great expertise." },
                { author: "Jane D.", rating: 5, comment: "Their fire safety training for our staff was engaging and very informative." },
                { author: "M. Patel", rating: 4, comment: "Good, reliable service for our annual extinguisher checks." },
                { author: "Cape Town Office", rating: 5, comment: "Very happy with their service. They make compliance simple." },
                { author: "Local Guesthouse", rating: 5, comment: "Friendly, efficient, and they provide all the necessary paperwork on the spot." },
                { author: "School Admin", rating: 5, comment: "We trust them to keep our school safe and compliant. Excellent service every year." },
                { author: "Maria S.", rating: 5, comment: "The risk assessment they did was incredibly detailed and helpful." },
                { author: "Chris H.", rating: 4, comment: "Solid service. They know their stuff when it comes to fire safety." },
                { author: "Events Venue", rating: 5, comment: "They help us ensure every event is safe and meets all regulations." },
                { author: "Body Corporate", rating: 5, comment: "Reliable partner for managing the fire safety of our entire building." }
            ],
            photos: ["https://picsum.photos/seed/firesafety4/600/400"],
            avatarSeed: "cape-fire-compliance"
        }
    ],
    dressmakers: [
        {
            id: "sew-elegant-jhb",
            name: "Sew Elegant JHB",
            location: "Rosebank, Johannesburg",
            description: "Expert dressmaking and alterations for all occasions. We create custom wedding gowns, matric dance dresses, and provide professional tailoring for a perfect fit.",
            rating: 4.9,
            reviews: 13,
            isProVerified: true,
            yearsInBusiness: 15,
            employees: 5,
            businessHours: "By Appointment Only",
            tags: ["Wedding Gowns", "Matric Dresses", "Alterations", "Tailoring"],
            reviewData: [
                { author: "Thandi M.", rating: 5, comment: "They made my wedding dress and it was absolutely perfect. The attention to detail was amazing." },
                { author: "Jessica P.", rating: 5, comment: "My matric dance dress was a dream come true. Exactly what I wanted." },
                { author: "Sarah L.", rating: 5, comment: "The best tailor in Joburg. They altered my suit to perfection." },
                { author: "Naledi R.", rating: 4, comment: "Beautiful work, but it took a bit longer than expected. Worth the wait though." },
                { author: "Emily K.", rating: 5, comment: "I've had several dresses made here. The quality is always exceptional." },
                { author: "Mother of the Bride", rating: 5, comment: "Created a stunning outfit for me for my daughter's wedding. I felt so elegant." },
                { author: "Mark T.", rating: 5, comment: "They are masters at what they do. I won't go anywhere else for alterations." },
                { author: "Lerato S.", rating: 5, comment: "They rescued a dress I bought online that didn't fit. Now it looks like it was made for me." },
                { author: "Chloe F.", rating: 5, comment: "So talented! Can't recommend them enough for custom designs." },
                { author: "A. Williams", rating: 4, comment: "Very professional service. A bit pricey but the quality is worth it." },
                { author: "Zoe B.", rating: 5, comment: "Thank you for my beautiful dress! I received so many compliments." },
                { author: "Fashion Student", rating: 5, comment: "I learn so much just by seeing their work. True artists." },
                { author: "David G.", rating: 5, comment: "Professional tailoring for men's suits. Excellent fit." }
            ],
            photos: ["https://picsum.photos/seed/dress1/600/400"],
            avatarSeed: "sew-elegant-logo"
        },
        {
            id: "the-alteration-studio",
            name: "The Alteration Studio",
            location: "Sea Point, Cape Town",
            description: "From simple hemming to complex resizing, we provide high-quality clothing alterations for men and women. Bring your garments for a professional finish and a perfect fit.",
            rating: 4.8,
            reviews: 11,
            isProVerified: true,
            yearsInBusiness: 10,
            employees: 3,
            businessHours: "Mon-Sat, 9am-6pm",
            tags: ["Hemming", "Resizing", "Tailoring", "Repairs"],
            reviewData: [
                { author: "John S.", rating: 5, comment: "Fast, professional, and my suit fits perfectly now. Highly recommend their services." },
                { author: "Anna C.", rating: 5, comment: "They altered my bridesmaid dress in two days. Great service and very friendly." },
                { author: "Peter V.", rating: 4, comment: "Did a good job on my jeans. A little on the expensive side but the quality is there." },
                { author: "Lisa M.", rating: 5, comment: "My go-to place for all my alterations. They are reliable and the work is always perfect." },
                { author: "James H.", rating: 5, comment: "Excellent attention to detail. They really know what they're doing." },
                { author: "Fashionista", rating: 5, comment: "They understand modern cuts and styles. I trust them with my designer clothes." },
                { author: "Mr. Jones", rating: 5, comment: "Quick and efficient service. They hemmed three pairs of trousers for me while I waited." },
                { author: "Karen W.", rating: 5, comment: "I wouldn't trust anyone else with my clothes. They are simply the best." },
                { author: "Busy Professional", rating: 4, comment: "Reliable and convenient. They always get the job done right." },
                { author: "Sarah B.", rating: 5, comment: "Saved my favorite dress! The repair is invisible. Thank you!" },
                { author: "Michael T.", rating: 5, comment: "Perfect fit every time. Great service." }
            ],
            photos: ["https://picsum.photos/seed/dress2/600/400"],
            avatarSeed: "alteration-studio-logo"
        }
    ],
    embroidery: [
        {
            id: "stitch-it-pro",
            name: "Stitch-It Pro",
            location: "Pretoria, Gauteng",
            description: "Custom embroidery for corporate branding, team uniforms, and personalized gifts. We offer high-quality digitizing and stitching on a wide range of garments and fabrics.",
            rating: 4.7,
            reviews: 10,
            isProVerified: true,
            yearsInBusiness: 7,
            employees: 6,
            businessHours: "Mon-Fri, 8:30am-5pm",
            tags: ["Corporate Branding", "Uniforms", "Personalized Gifts", "Digitizing"],
            reviewData: [
                { author: "ABC Corp", rating: 5, comment: "Our company shirts look fantastic with our logo embroidered. The quality is top-notch." },
                { author: "School Sports Team", rating: 5, comment: "They embroidered our team logo on our jackets. The kids love them!" },
                { author: "Promotions Co.", rating: 4, comment: "Good quality embroidery. Turnaround time was a bit longer than we hoped but the result was great." },
                { author: "New Mom", rating: 5, comment: "They embroidered a beautiful personalized baby blanket for me. It's so special." },
                { author: "Gifting Company", rating: 5, comment: "We use them for all our personalized corporate gifts. They are reliable and the quality is always excellent." },
                { author: "J. Botha", rating: 5, comment: "The stitching is very neat and detailed. Very professional work." },
                { author: "Marketing Manager", rating: 5, comment: "Great for promotional items like caps and bags. They make our brand look good." },
                { author: "B&B Owner", rating: 4, comment: "Had our gowns and towels embroidered. Looks very professional." },
                { author: "Event Planner", rating: 5, comment: "They are my go-to for last-minute embroidery needs. Always helpful." },
                { author: "Chris P.", rating: 5, comment: "Excellent quality and service. I will definitely use them again." }
            ],
            photos: ["https://picsum.photos/seed/emb1/600/400"],
            avatarSeed: "stitch-it-pro-logo"
        }
    ],
    "cake-shops": [
        {
            id: "the-sweet-spot-bakery",
            name: "The Sweet Spot Bakery",
            location: "Durbanville, Cape Town",
            description: "Artisanal bakery specializing in custom cakes for weddings, birthdays, and special occasions. We also offer a delicious range of cupcakes, pastries, and daily treats.",
            rating: 4.9,
            reviews: 15,
            isProVerified: true,
            yearsInBusiness: 5,
            employees: 8,
            businessHours: "Tue-Sat, 9am-4pm",
            tags: ["Custom Cakes", "Wedding Cakes", "Birthday Cakes", "Cupcakes"],
            reviewData: [
                { author: "Sarah P.", rating: 5, comment: "The most beautiful and delicious wedding cake! Our guests couldn't stop talking about it." },
                { author: "Birthday Mom", rating: 5, comment: "They created an amazing themed cake for my son's birthday. It was the star of the party." },
                { author: "John D.", rating: 5, comment: "Their cupcakes are dangerously good. Best in Cape Town!" },
                { author: "Event Planner", rating: 5, comment: "I order from them for all my events. The quality is always exceptional and they are so reliable." },
                { author: "Anonymous", rating: 4, comment: "Delicious cake, but communication for the custom order could have been a bit better." },
                { author: "Mary-Anne", rating: 5, comment: "A true gem in Durbanville. Their pastries are divine." },
                { author: "Corporate Event", rating: 5, comment: "Ordered branded cupcakes for a product launch. They were a huge hit." },
                { author: "Regular Customer", rating: 5, comment: "I can't drive past without stopping for a treat. Everything is delicious." },
                { author: "Foodie", rating: 5, comment: "The quality of their ingredients really shines through. You can taste the difference." },
                { author: "Jason L.", rating: 5, comment: "They made a magnificent cake for our anniversary. It looked and tasted incredible." },
                { author: "T. Naidoo", rating: 4, comment: "Cake was lovely. A bit pricey but you pay for quality." },
                { author: "Engaged Couple", rating: 5, comment: "The cake tasting was such a fun and delicious experience. Can't wait for our wedding cake!" },
                { author: "C. van Wyk", rating: 5, comment: "Best cheesecake I have ever had. Seriously." },
                { author: "Gift Giver", rating: 5, comment: "I ordered a box of cupcakes as a gift and they were beautifully packaged and so tasty." },
                { author: "Anniversary Celebration", rating: 5, comment: "The cake was the perfect centerpiece for our celebration. Thank you!" }
            ],
            photos: ["https://picsum.photos/seed/cake1/600/400", "https://picsum.photos/seed/cake2/600/400"],
            avatarSeed: "sweet-spot-bakery-logo"
        }
    ],
    caterers: [
        {
            id: "gourmet-gatherings-cpt",
            name: "Gourmet Gatherings CPT",
            location: "Cape Town",
            description: "Boutique catering for corporate events, weddings, and private parties. We create bespoke menus using fresh, local ingredients to make your event unforgettable.",
            rating: 4.8,
            reviews: 13,
            isProVerified: true,
            yearsInBusiness: 9,
            employees: 12,
            businessHours: "By Appointment",
            tags: ["Corporate Catering", "Wedding Catering", "Private Parties", "Bespoke Menus"],
            reviewData: [
                { author: "XYZ Events", rating: 5, comment: "Their food is always a highlight at our corporate functions. Professional, creative, and delicious." },
                { author: "Happy Bride", rating: 5, comment: "The food at our wedding was exquisite. So many of our guests commented on it. Thank you!" },
                { author: "40th Birthday", rating: 5, comment: "The canapés were incredible. It really elevated my birthday party." },
                { author: "Product Launch", rating: 4, comment: "Great food and presentation. A few logistical hiccups but they were resolved quickly." },
                { author: "P. Adams", rating: 5, comment: "From the planning to the execution, everything was seamless. The food was divine." },
                { author: "Wine Estate", rating: 5, comment: "They understand food and wine pairing perfectly. A great partner for our events." },
                { author: "Art Gallery Opening", rating: 5, comment: "The food was as beautiful as the art. Elegant and delicious." },
                { author: "The Johnson Family", rating: 5, comment: "We hired them for a family reunion. The harvest table was a huge hit!" },
                { author: "Conference Organizer", rating: 4, comment: "Reliable service for our conference catering. The attendees enjoyed the food." },
                { author: "Film Shoot", rating: 5, comment: "Provided catering for our film crew. They were flexible and the food was great." },
                { author: "Charity Gala", rating: 5, comment: "Exceptional food and service for our fundraising gala. A pleasure to work with." },
                { author: "T. Ndlovu", rating: 5, comment: "The quality of the ingredients and the presentation is always top-class." },
                { author: "International Delegation", rating: 5, comment: "They showcased the best of South African cuisine for our guests. Everyone was impressed." }
            ],
            photos: ["https://picsum.photos/seed/cater1/600/400"],
            avatarSeed: "gourmet-gatherings-logo"
        },
        {
            id: "soweto-feasts",
            name: "Soweto Feasts Catering",
            location: "Soweto",
            description: "Authentic South African cuisine for any event. Specializing in traditional dishes and braais for weddings, parties, and corporate functions.",
            rating: 4.9,
            reviews: 14,
            isProVerified: true,
            serviceLocations: ["soweto", "johannesburg"],
            yearsInBusiness: 12,
            employees: 10,
            businessHours: "By Appointment",
            tags: ["Traditional Cuisine", "Braai Catering", "Shisanyama", "Event Catering"],
            reviewData: [
                { author: "Thabo M.", rating: 5, comment: "The best traditional food I've had at an event. Our international guests loved it!" },
                { author: "Lerato's Wedding", rating: 5, comment: "They catered our wedding and the food was incredible. Proper, delicious home-style cooking." },
                { author: "Corporate Year-End", rating: 5, comment: "The braai they did for our year-end function was a huge success. Everyone loved it." },
                { author: "Jabu's 50th", rating: 5, comment: "Authentic, flavourful, and plenty of it! The perfect food for a celebration." },
                { author: "S. Gumede", rating: 4, comment: "Very good food. The setup took a little longer than planned but they made up for it." },
                { author: "Community Event", rating: 5, comment: "They are our go-to caterers for all our community events. The food is always a hit." },
                { author: "Tourist Group", rating: 5, comment: "A fantastic introduction to South African food for our tour group. They loved the experience." },
                { author: "N. Cele", rating: 5, comment: "The flavour of their shisanyama is just perfect. You can taste the quality." },
                { author: "Family Gathering", rating: 5, comment: "It felt like a family celebration with their food. So much love and care goes into it." },
                { author: "Peter J.", rating: 5, comment: "Reliable, delicious, and generous portions. What more could you ask for?" },
                { author: "Sports Club", rating: 4, comment: "Great food for our awards evening. Everyone was happy." },
                { author: "Music Festival", rating: 5, comment: "They handled the catering for our VIP area. The food was amazing." },
                { author: "Gogo Dlamini", rating: 5, comment: "Tastes like home. Beautiful food." },
                { author: "Sipho's Tombstone Unveiling", rating: 5, comment: "They provided a respectful and wonderful catering service for our family. The food was perfect." }
            ],
            photos: ["https://picsum.photos/seed/soweto-cater/600/400"],
            avatarSeed: "gourmet-gatherings-logo"
        }
    ],
    groomers: [
        {
            id: "the-dapper-dog-jhb",
            name: "The Dapper Dog JHB",
            location: "Sandton, Johannesburg",
            description: "Professional and gentle pet grooming for dogs of all sizes. Our services include washing, clipping, nail trimming, and de-shedding in a calm and clean environment.",
            rating: 4.9,
            reviews: 12,
            isProVerified: true,
            yearsInBusiness: 6,
            employees: 4,
            businessHours: "Tue-Sat, 8am-5pm",
            tags: ["Dog Grooming", "Pet Spa", "Nail Trimming", "De-shedding"],
            reviewData: [
                { author: "Lindiwe T.", rating: 5, comment: "My fluffy dog always comes back looking and smelling amazing. The staff are so patient and caring." },
                { author: "Max's Human", rating: 5, comment: "They are so good with my anxious dog. He comes back happy and looking handsome." },
                { author: "Mrs. van der Walt", rating: 5, comment: "The best grooming my dogs have ever had. The salon is clean and the staff are wonderful." },
                { author: "First-timer", rating: 5, comment: "It was my puppy's first groom and they were so gentle. A great experience." },
                { author: "J. Peters", rating: 4, comment: "Good groom, but they are very popular so you need to book well in advance." },
                { author: "Bella's Mom", rating: 5, comment: "Bella loves going to 'the spa'. She always looks so proud when she comes out." },
                { author: "Rescue Dog Owner", rating: 5, comment: "They were incredibly patient with my rescue who is scared of everything. Highly recommend." },
                { author: "David S.", rating: 5, comment: "Professional service and you can see they genuinely love dogs." },
                { author: "The Poodle Owner", rating: 5, comment: "They do a perfect poodle cut every time. True professionals." },
                { author: "Ms. Jacobs", rating: 4, comment: "My dog looks great. The pricing is a bit high but the quality is worth it." },
                { author: "Regular Client", rating: 5, comment: "We've been coming here for years. Consistent, high-quality service." },
                { author: "Two Happy Dogs", rating: 5, comment: "Both my dogs look and smell divine. Thank you!" }
            ],
            photos: ["https://picsum.photos/seed/groom1/600/400"],
            avatarSeed: "dapper-dog-logo"
        }
    ],
    "pet-sitters": [
        {
            id: "happy-paws-pet-sitting",
            name: "Happy Paws Pet Sitting",
            location: "Johannesburg North",
            description: "Reliable and loving pet sitting services in the comfort of your own home. We also offer daily dog walking and check-in visits to keep your pets happy while you're away.",
            rating: 5.0,
            reviews: 11,
            isProVerified: true,
            yearsInBusiness: 4,
            employees: 3,
            businessHours: "By Appointment",
            tags: ["In-home Pet Sitting", "Dog Walking", "Cat Sitting"],
            reviewData: [
                { author: "Mike V.", rating: 5, comment: "I can travel without worrying about my cats. They send me daily updates and the cats are always happy and relaxed when I get back." },
                { author: "Dog Owner", rating: 5, comment: "Our dog walker is fantastic. So reliable and our dog absolutely adores her." },
                { author: "Anxious Pet Parent", rating: 5, comment: "I was so nervous leaving my pets, but they were amazing. The photo updates were so reassuring." },
                { author: "The Wilsons", rating: 5, comment: "Peace of mind when we go on holiday. It's so much better than a kennel." },
                { author: "Mrs. Green", rating: 5, comment: "A truly professional and trustworthy service. I recommend them to all my friends." },
                { author: "Two Cats & a Dog", rating: 5, comment: "They looked after our whole furry family. Came home to happy, well-cared-for pets." },
                { author: "Frequent Traveller", rating: 5, comment: "I use them all the time for business trips. Completely reliable and my dog loves them." },
                { author: "Last-minute booking", rating: 5, comment: "They helped me out with a last-minute booking and were so accommodating." },
                { author: "Cat Mom", rating: 5, comment: "So much better than asking a neighbour. My cat was much less stressed." },
                { author: "R. Singh", rating: 5, comment: "Excellent service. You can tell they are passionate about animals." },
                { author: "Elderly Dog Owner", rating: 5, comment: "They take such good care of my old dog who needs special attention. Wonderful people." }
            ],
            photos: ["https://picsum.photos/seed/petsit1/600/400"],
            avatarSeed: "happy-paws-logo"
        }
    ],
    "tour-operators": [
        {
            id: "safari-scapes-sa",
            name: "Safari-Scapes SA",
            location: "Johannesburg & Kruger Park",
            description: "Specialists in tailor-made Kruger National Park safaris and tours. We offer guided game drives, luxury lodge accommodation, and unforgettable wildlife experiences.",
            rating: 4.9,
            reviews: 13,
            isProVerified: true,
            yearsInBusiness: 18,
            employees: 20,
            businessHours: "Mon-Sat, 8am-6pm",
            tags: ["Kruger Safaris", "Guided Game Drives", "Wildlife Tours"],
            reviewData: [
                { author: "Anna S.", rating: 5, comment: "The best safari of my life! Our guide was incredibly knowledgeable and we saw the Big 5. Highly recommend." },
                { author: "American Tourist", rating: 5, comment: "An unforgettable experience from start to finish. The accommodation was incredible and the wildlife sightings were breathtaking." },
                { author: "Family from UK", rating: 5, comment: "Our guide was amazing with the kids and made the trip so educational and fun for them." },
                { author: "Honeymoon Couple", rating: 5, comment: "The most romantic and adventurous honeymoon. Everything was perfectly organized." },
                { author: "Wildlife Photographer", rating: 5, comment: "The guide knew all the best spots for photography. I got some incredible shots." },
                { author: "J. Peterson", rating: 4, comment: "A fantastic tour. The vehicle was a bit cramped but the sightings made up for it." },
                { author: "First-time Safari", rating: 5, comment: "As a first-timer, I was blown away. They take care of everything. You just have to enjoy the experience." },
                { author: "The Millers", rating: 5, comment: "This was our third safari with them. They never disappoint." },
                { author: "German Couple", rating: 5, comment: "The guide's passion for the bush is infectious. We learned so much." },
                { author: "Solo Traveller", rating: 5, comment: "Felt completely safe and well-cared-for as a solo traveller. The group was great." },
                { author: "SA Local", rating: 5, comment: "Even as a South African, I saw Kruger in a new light. Their expertise is invaluable." },
                { author: "B. Cole", rating: 5, comment: "The whole trip was seamless, from the booking to the final drop-off." },
                { author: "Nature Lover", rating: 5, comment: "A truly immersive wildlife experience. Can't wait to go back." }
            ],
            photos: ["https://picsum.photos/seed/tour1/600/400", "https://picsum.photos/seed/tour2/600/400"],
            avatarSeed: "safari-scapes-logo"
        }
    ],
    "travel-agents": [
        {
            id: "global-journeys-travel",
            name: "Global Journeys Travel",
            location: "Online / Nationwide",
            description: "Your personal travel experts for local and international holidays. We find the best deals on flights, accommodation, and tour packages to create your dream vacation.",
            rating: 4.8,
            reviews: 14,
            isProVerified: true,
            yearsInBusiness: 10,
            employees: 15,
            businessHours: "Mon-Fri, 9am-5pm",
            tags: ["International Holidays", "Local Travel", "Flight Deals", "Tour Packages"],
            reviewData: [
                { author: "David C.", rating: 5, comment: "They planned our family trip to Thailand perfectly. Everything was seamless and they saved us a lot of money." },
                { author: "Honeymooners", rating: 5, comment: "Our honeymoon to the Maldives was a dream. They thought of every little detail." },
                { author: "Corporate Travel", rating: 5, comment: "I use them for all my business travel. They are efficient, professional and always find the best routes." },
                { author: "The Watsons", rating: 4, comment: "Great trip to Mauritius. One of the hotel transfers was a bit late, but otherwise everything was perfect." },
                { author: "Solo Adventurer", rating: 5, comment: "They helped me plan a complex backpacking trip through South America. Their advice was invaluable." },
                { author: "Family Holiday", rating: 5, comment: "So much easier than trying to book everything myself. They take all the stress out of travel planning." },
                { author: "Susan B.", rating: 5, comment: "My consultant was amazing. So patient and found us a fantastic deal." },
                { author: "Island Getaway", rating: 5, comment: "Zanzibar was incredible. Thank you for the perfect recommendation." },
                { author: "First-time International", rating: 5, comment: "I was nervous about my first overseas trip, but they made it so easy and stress-free." },
                { author: "Group Tour", rating: 4, comment: "Organized a great tour for our group of friends. A few small hitches but overall a great experience." },
                { author: "Cruise Booking", rating: 5, comment: "They found us a great deal on a Mediterranean cruise. Excellent service." },
                { author: "Local Weekend", rating: 5, comment: "Even for a local weekend away in the Drakensberg, their service was fantastic." },
                { author: "A. Patel", rating: 5, comment: "I will never book a holiday by myself again. They are worth every cent." },
                { author: "Retirement Trip", rating: 5, comment: "Planned our dream retirement trip to Italy. It was perfect." }
            ],
            photos: ["https://picsum.photos/seed/travel1/600/400"],
            avatarSeed: "global-journeys-logo"
        }
    ],
    "air-conditioning": [
      {
        id: "ac-comfort-zone",
        name: "AC Comfort Zone",
        location: "Sandton, Johannesburg",
        description: "Specialists in residential and commercial air conditioning installation, servicing, and repairs. We work with all major brands to keep you cool in summer and warm in winter.",
        rating: 4.8,
        reviews: 13,
        isProVerified: true,
        yearsInBusiness: 10,
        employees: 8,
        businessHours: "Mon-Sat, 8am-5pm",
        tags: ["AC Installation", "AC Repairs", "AC Servicing", "Commercial HVAC"],
        reviewData: [
          { author: "J. Naidoo", rating: 5, comment: "Fast installation and very neat work. The new unit works perfectly. Very happy with their service." },
          { author: "Office Manager", rating: 5, comment: "They service all the aircon units in our building. Always reliable and professional." },
          { author: "Mrs. Van Rooyen", rating: 4, comment: "Good service, my aircon is working again. A bit pricey but they were available immediately." },
          { author: "Sandton Home", rating: 5, comment: "Installed a central air system for us. The team was fantastic and very knowledgeable." },
          { author: "Retail Shop", rating: 5, comment: "Our shop aircon broke down on a hot day. They came out within hours and fixed it. Lifesavers!" },
          { author: "B. Khumalo", rating: 5, comment: "Annual service was done quickly and professionally. The unit is running much more efficiently now." },
          { author: "New Installation", rating: 5, comment: "Very clean and professional installation of three new units. Highly recommend." },
          { author: "Emergency Repair", rating: 5, comment: "My AC unit was leaking water. They identified and fixed the problem quickly." },
          { author: "T. Smith", rating: 4, comment: "Happy with the repair. Communication could have been a little better regarding arrival time." },
          { author: "Property Manager", rating: 5, comment: "They are on our list of preferred suppliers. Always reliable." },
          { author: "G. Meyer", rating: 5, comment: "Excellent advice on which unit to choose for our space. Very helpful." },
          { author: "Cool Again", rating: 5, comment: "So happy to have a working aircon again. Thanks for the fast service!" },
          { author: "Five Stars", rating: 5, comment: "Five-star service from start to finish. Wouldn't use anyone else." }
        ],
        photos: ["https://picsum.photos/seed/ac1/600/400"],
        avatarSeed: "ac-comfort-logo"
      },
      {
        id: "cool-breeze-air",
        name: "Cool Breeze Air Conditioning",
        location: "Durban, KZN",
        description: "Your local experts for aircon regassing, repairs, and new installations. We offer competitive pricing and fast, friendly service to the greater Durban area.",
        rating: 4.7,
        reviews: 11,
        isProVerified: true,
        yearsInBusiness: 7,
        employees: 5,
        businessHours: "Mon-Fri, 8am-5pm",
        tags: ["AC Regassing", "Aircon Repairs", "New Installations", "Durban"],
        reviewData: [
          { author: "Mike L.", rating: 5, comment: "My aircon wasn't cooling. They came out the same day, found the leak, and regassed it. Excellent service." },
          { author: "Durban Homeowner", rating: 5, comment: "A must-have service in Durban! They keep our aircon running perfectly." },
          { author: "P. Govender", rating: 4, comment: "Good, honest service. The technician explained the problem clearly." },
          { author: "Beachfront Apt", rating: 5, comment: "Installed a new sea-side resistant unit for us. Great advice and workmanship." },
          { author: "Umhlanga Office", rating: 5, comment: "Reliable and affordable. They service our office units every year." },
          { author: "S. Mkhize", rating: 5, comment: "Fast and friendly service. My aircon is ice cold again!" },
          { author: "C. Botha", rating: 4, comment: "The repair took two visits but they got it sorted. Happy with the outcome." },
          { author: "KZN Heat", rating: 5, comment: "Couldn't survive a Durban summer without these guys. Always there when you need them." },
          { author: "Great Value", rating: 5, comment: "Their service fee was very reasonable compared to other quotes I got." },
          { author: "Honest Technician", rating: 5, comment: "I thought I needed a new unit, but they were honest and said it just needed a good service. Saved me thousands." },
          { author: "Happy Customer", rating: 5, comment: "Excellent work. I will be using them for my annual service from now on." }
        ],
        photos: ["https://picsum.photos/seed/ac2/600/400"],
        avatarSeed: "ac-comfort-logo"
      },
       {
            id: "alberton-air-pros",
            name: "Alberton Air Pros",
            location: "Alberton",
            description: "Local experts in {service} installation and maintenance for homes and offices in Alberton. We guarantee cool summers and warm winters.",
            rating: 4.8,
            reviews: 12,
            isProVerified: true,
            serviceLocations: ["alberton", "germiston"],
            yearsInBusiness: 8,
            employees: 4,
            businessHours: "Mon-Fri, 8am-5pm",
            tags: ["Aircon Installation", "AC Maintenance", "Residential AC", "Alberton"],
            reviewData: [
                { author: "Mrs. Smith", rating: 5, comment: "Installed our new aircon unit just in time for summer. Very professional and clean." },
                { author: "Alberton Resident", rating: 5, comment: "Fast and reliable service. My go-to for aircon issues." },
                { author: "Local Business", rating: 5, comment: "They keep our office cool all year round. Great maintenance contract." },
                { author: "John P.", rating: 4, comment: "Good work. The technician arrived a bit later than scheduled but did a great job." },
                { author: "Leaking Unit", rating: 5, comment: "They fixed my leaking aircon unit quickly. Very happy." },
                { author: "New Installation", rating: 5, comment: "Professional installation and they cleaned up perfectly afterwards." },
                { author: "M. van der Merwe", rating: 5, comment: "Excellent service from a local company. Will support them again." },
                { author: "T. Khumalo", rating: 5, comment: "Very happy with their work. My aircon is working like new." },
                { author: "Fair Pricing", rating: 4, comment: "Got a few quotes and theirs was the most reasonable. The work was good." },
                { author: "Annual Service", rating: 5, comment: "They do my annual service every year. Always professional and thorough." },
                { author: "Helpful Technician", rating: 5, comment: "The technician gave me some great tips on how to use my aircon more efficiently." },
                { author: "Highly Recommended", rating: 5, comment: "I would highly recommend Alberton Air Pros to anyone." }
            ],
            photos: ["https://picsum.photos/seed/albertonair/600/400"],
            avatarSeed: "ac-comfort-logo"
      }
    ],
    "aluminium-doors-and-windows": [
      {
        id: "alum-designs-pta",
        name: "Alu-Designs PTA",
        location: "Pretoria, Gauteng",
        description: "Custom manufacturers and installers of high-quality aluminium windows, sliding doors, folding doors, and enclosures. Modernize your home with our durable and stylish solutions.",
        rating: 4.9,
        reviews: 14,
        isProVerified: true,
        yearsInBusiness: 15,
        employees: 20,
        businessHours: "Mon-Fri, 8am-5pm",
        tags: ["Aluminium Windows", "Sliding Doors", "Folding Doors", "Enclosures"],
        reviewData: [
          { author: "Mrs. Van der Merwe", rating: 5, comment: "The new folding doors have completely transformed our living area. The quality and installation were top-notch." },
          { author: "The Architect", rating: 5, comment: "I use Alu-Designs for many of my projects. They are reliable and their products are excellent quality." },
          { author: "New Home Build", rating: 5, comment: "Supplied all the windows and doors for our new house. The quality is exceptional." },
          { author: "Renovator", rating: 5, comment: "Replaced our old steel windows with aluminium. What a difference! The house is warmer and quieter." },
          { author: "Mr. Pillay", rating: 4, comment: "Beautiful product. There was a slight delay in delivery but they communicated well." },
          { author: "Patio Enclosure", rating: 5, comment: "Our new enclosed patio is our favorite room in the house now. Excellent work." },
          { author: "K. Botha", rating: 5, comment: "Their attention to detail is impressive. The installation was perfect." },
          { author: "Modern Look", rating: 5, comment: "Gave our home a much-needed modern update. Very happy." },
          { author: "Office Upgrade", rating: 5, comment: "Replaced all the windows in our office block. Big improvement and the team was very professional." },
          { author: "Builder", rating: 5, comment: "Reliable supplier with great products. I recommend them to my clients." },
          { author: "S. Naidoo", rating: 5, comment: "I love my new sliding doors. They glide so smoothly." },
          { author: "Secure and Stylish", rating: 5, comment: "The windows are not only stylish but also very secure. Great peace of mind." },
          { author: "Great Investment", rating: 5, comment: "A great investment in our property. The quality is obvious." },
          { author: "Pta Homeowner", rating: 5, comment: "Best aluminium window company in Pretoria. Look no further." }
        ],
        photos: ["https://picsum.photos/seed/alum1/600/400", "https://picsum.photos/seed/alum2/600/400"],
        avatarSeed: "alum-designs-logo"
      },
       {
            id: "roodepoort-glass-aluminium",
            name: "Roodepoort Glass & Aluminium",
            location: "Roodepoort",
            description: "Specialists in custom aluminium windows and doors. We offer competitive pricing and professional installation for all {service}.",
            rating: 4.7,
            reviews: 12,
            isProVerified: true,
            serviceLocations: ["roodepoort", "krugersdorp", "randburg"],
            yearsInBusiness: 10,
            employees: 7,
            businessHours: "Mon-Fri, 8am-5pm",
            tags: ["Aluminium Windows", "Stacking Doors", "Sliding Doors", "Repairs"],
            reviewData: [
                { author: "David", rating: 5, comment: "The new stacking doors are amazing. Great quality and installation was perfect." },
                { author: "West Rand Home", rating: 5, comment: "Replaced our old wooden windows. The house looks so much more modern now." },
                { author: "Mrs. Fouche", rating: 4, comment: "Good service and a fair price. The team was very professional." },
                { author: "Renovation Project", rating: 5, comment: "They did all the windows and doors for our renovation. Very happy with the result." },
                { author: "P. Molefe", rating: 5, comment: "Excellent work and good communication throughout the process." },
                { author: "Patio Enclosure", rating: 5, comment: "Our new enclosed patio is fantastic. They did a really neat job." },
                { author: "C. Grobler", rating: 4, comment: "The windows are great quality. The installation took a day longer than planned." },
                { author: "Local Business", rating: 5, comment: "Replaced our old shopfront. It looks professional and modern now." },
                { author: "Happy Customer", rating: 5, comment: "I would recommend them to anyone looking for aluminium windows." },
                { author: "Great Team", rating: 5, comment: "The installation team was friendly, efficient, and very tidy." },
                { author: "Value for Money", rating: 5, comment: "Got a few quotes and they were the most competitive. The quality is still excellent." },
                { author: "Roodepoort Resident", rating: 5, comment: "Great to have a reliable local company. Very happy with their work." }
            ],
            photos: ["https://picsum.photos/seed/roodepoortalum/600/400"],
            avatarSeed: "alum-designs-logo"
        }
    ],
    awnings: [
      {
        id: "shade-masters-sa",
        name: "Shade Masters SA",
        location: "Johannesburg",
        description: "We supply and install a wide range of awnings, including retractable awnings, fixed awnings, and shade sails for patios, businesses, and pools.",
        rating: 4.7,
        reviews: 11,
        isProVerified: true,
        yearsInBusiness: 12,
        employees: 10,
        businessHours: "Mon-Fri, 8am-5pm",
        tags: ["Retractable Awnings", "Fixed Awnings", "Shade Sails", "Patio Covers"],
        reviewData: [
          { author: "Cafe Owner", rating: 5, comment: "The new retractable awning for our patio is perfect. Great quality and the installation team was very professional." },
          { author: "Homeowner", rating: 5, comment: "Installed a beautiful fixed awning over our front door. It's really improved the look of our house." },
          { author: "Pool Area", rating: 5, comment: "The shade sail over our pool area is a game-changer. We can actually use the area in the heat of the day now." },
          { author: "Mr. Singh", rating: 4, comment: "Good product. The sales process was a bit slow but the installation was efficient." },
          { author: "JHB Resident", rating: 5, comment: "Very happy with my new patio awning. It's extended our living space." },
          { author: "L. Tladi", rating: 5, comment: "Excellent quality and a very professional team. Highly recommend." },
          { author: "Restaurant", rating: 5, comment: "Our customers love the new shaded seating area. It's been great for business." },
          { author: "G. Venter", rating: 4, comment: "The awning is great. Getting the final quote took a while." },
          { author: "Quality Product", rating: 5, comment: "You can feel the quality of the materials. This awning is built to last." },
          { author: "Great Addition", rating: 5, comment: "A great addition to our home. We should have done it years ago." },
          { author: "Five Stars", rating: 5, comment: "Five-star service and a five-star product. Very happy." }
        ],
        photos: ["https://picsum.photos/seed/awning1/600/400"],
        avatarSeed: "shade-masters-logo"
      }
    ],
    balustrades: [
      {
        id: "modern-rails-cpt",
        name: "Modern Rails CPT",
        location: "Cape Town",
        description: "Specialists in the design and installation of modern balustrades. We offer frameless glass, stainless steel, and custom-designed solutions for staircases, balconies, and pools.",
        rating: 4.9,
        reviews: 13,
        isProVerified: true,
        yearsInBusiness: 9,
        employees: 12,
        businessHours: "Mon-Fri, 8:30am-5pm",
        tags: ["Frameless Glass", "Stainless Steel", "Staircases", "Balconies"],
        reviewData: [
          { author: "New Homeowner", rating: 5, comment: "The frameless glass balustrade on our balcony is stunning. It completely opened up the view. Excellent workmanship." },
          { author: "Architect", rating: 5, comment: "Their work is precise and elegant. They are my first choice for modern balustrades." },
          { author: "The Wilsons", rating: 5, comment: "Installed a stainless steel balustrade on our new staircase. It's a real feature." },
          { author: "Pool Safety", rating: 5, comment: "The glass pool fence is safe, strong, and looks incredible. So much better than a traditional fence." },
          { author: "A. Hendricks", rating: 4, comment: "Beautiful result. The project ran a little over schedule but it was worth it." },
          { author: "Luxury Home", rating: 5, comment: "The quality of their work matches the quality of the homes we build. Exceptional." },
          { author: "Renovator", rating: 5, comment: "Replaced our old wooden balustrade. The difference is amazing. The house feels so much more modern." },
          { author: "J. du Plessis", rating: 5, comment: "Very professional from the quoting stage right through to installation." },
          { author: "Sleek and Modern", rating: 5, comment: "If you want a sleek, modern look, these are the guys to call." },
          { author: "Camps Bay View", rating: 5, comment: "Didn't want to obstruct the view, and their frameless glass was the perfect solution." },
          { author: "Meticulous Work", rating: 5, comment: "The installation team was meticulous. Every panel is perfectly aligned." },
          { author: "Highly Recommended", rating: 5, comment: "I can't recommend them highly enough. The quality is outstanding." },
          { author: "Happy Client", rating: 5, comment: "A very happy client. The result exceeded my expectations." }
        ],
        photos: ["https://picsum.photos/seed/rail1/600/400"],
        avatarSeed: "modern-rails-logo"
      }
    ],
    "bathroom-renovations": [
      {
        id: "dream-bath-reno",
        name: "Dream Bath Renovations",
        location: "Johannesburg North",
        description: "Complete bathroom renovation specialists. From design and tiling to plumbing and installation, we handle your entire project from start to finish.",
        rating: 4.8,
        reviews: 12,
        isProVerified: true,
        yearsInBusiness: 11,
        employees: 9,
        businessHours: "Mon-Fri, 8am-5pm",
        tags: ["Full Renovations", "Tiling", "Plumbing", "Bathroom Design"],
        reviewData: [
          { author: "The Smiths", rating: 5, comment: "They transformed our old, dated bathroom into a modern masterpiece. We are so happy with the result." },
          { author: "Priya", rating: 5, comment: "Professional, on time, and the quality of their work is excellent. I highly recommend them." },
          { author: "J. Botha", rating: 4, comment: "The project took a week longer than planned, but the final result is beautiful." },
          { author: "New Bathroom", rating: 5, comment: "They managed the whole project which made it so stress-free for us. The team was great." },
          { author: "M. Nkosi", rating: 5, comment: "Their design ideas were fantastic. They created a much more functional and beautiful space." },
          { author: "Investment Property", rating: 5, comment: "A great renovation that has definitely added value to our property." },
          { author: "Attention to Detail", rating: 5, comment: "Their attention to detail with the tiling and finishes is very impressive." },
          { author: "Clean and Tidy", rating: 5, comment: "I was impressed with how clean and tidy they left the site every day." },
          { author: "Worth the money", rating: 5, comment: "A bathroom renovation is a big investment, and they made sure it was worth every cent." },
          { author: "Great Communication", rating: 4, comment: "Good communication throughout the project, keeping us updated on progress." },
          { author: "Dream Bathroom", rating: 5, comment: "I finally have my dream bathroom! Thank you to the whole team." },
          { author: "Highly Recommend", rating: 5, comment: "Would not hesitate to recommend them. A very professional company." }
        ],
        photos: ["https://picsum.photos/seed/bath1/600/400", "https://picsum.photos/seed/bath2/600/400"],
        avatarSeed: "dream-bath-logo"
      },
      {
            id: "benoni-bathrooms",
            name: "Benoni Bathrooms",
            location: "Benoni",
            description: "Your local specialists for complete {service}. We offer affordable packages for modernizing your bathroom, including tiling, plumbing, and fittings.",
            rating: 4.7,
            reviews: 10,
            isProVerified: true,
            serviceLocations: ["benoni", "boksburg", "kempton-park"],
            yearsInBusiness: 6,
            employees: 4,
            businessHours: "Mon-Sat, 8am-5pm",
            tags: ["Bathroom Packages", "Tiling", "Plumbing", "Affordable Renovations"],
            reviewData: [
                { author: "Mrs. Jones", rating: 5, comment: "My new bathroom is beautiful! They did a wonderful job and were very tidy." },
                { author: "First Home", rating: 5, comment: "We were on a tight budget and they offered a great package. The bathroom looks amazing." },
                { author: "D. Visser", rating: 4, comment: "Good value for money. A few small things needed touching up but they came back and sorted it out." },
                { author: "Benoni Resident", rating: 5, comment: "So glad I chose a local company. They were friendly, reliable, and did a great job." },
                { author: "Guest Bathroom", rating: 5, comment: "They did a quick and beautiful makeover of our guest bathroom." },
                { author: "P. Singh", rating: 5, comment: "Professional team and a great result. I'm very happy." },
                { author: "Rental Property", rating: 5, comment: "A cost-effective way to modernize the bathroom in my rental unit. It looks great." },
                { author: "A. Coetzee", rating: 4, comment: "The work is good. It was just a bit difficult to get hold of them sometimes." },
                { author: "Fresh Look", rating: 5, comment: "They gave my old bathroom a fresh, modern look without breaking the bank." },
                { author: "Happy Customer", rating: 5, comment: "A happy customer. Would use them again." }
            ],
            photos: ["https://picsum.photos/seed/benonibath/600/400"],
            avatarSeed: "dream-bath-logo"
        }
    ],
    blinds: [
      {
        id: "blind-ambition-za",
        name: "Blind Ambition",
        location: "Nationwide",
        description: "Your one-stop shop for all types of blinds, including Venetian, roller, Roman, and vertical blinds. We offer free measurements and quotes.",
        rating: 4.7,
        reviews: 14,
        isProVerified: true,
        yearsInBusiness: 15,
        employees: 30,
        businessHours: "Mon-Fri, 9am-5pm; Sat, 9am-1pm",
        tags: ["Venetian Blinds", "Roller Blinds", "Roman Blinds", "Vertical Blinds"],
        reviewData: [
          { author: "Linda G.", rating: 5, comment: "Great selection and the installation was quick and professional. The new blinds look fantastic." },
          { author: "New Office", rating: 5, comment: "Fitted our entire new office with vertical blinds. They look great and the service was excellent." },
          { author: "Home Makeover", rating: 4, comment: "The blinds have really updated the look of our home. There was a bit of a wait for the stock to arrive." },
          { author: "Mrs. Peters", rating: 5, comment: "The consultant who came to measure was very helpful and gave great advice." },
          { author: "J. Naidoo", rating: 5, comment: "I love my new wooden Venetian blinds. They add so much warmth to the room." },
          { author: "Block-out Blinds", rating: 5, comment: "The block-out roller blinds for our bedroom are a game-changer. Best sleep ever." },
          { author: "S. van Zyl", rating: 4, comment: "Good quality blinds. The installation team was a little late but did a good job." },
          { author: "Happy Customer", rating: 5, comment: "A very smooth process from getting a quote to the final installation." },
          { author: "Great Selection", rating: 5, comment: "They have a huge selection of fabrics and materials to choose from." },
          { author: "Affordable", rating: 5, comment: "Their prices were very competitive compared to other quotes I received." },
          { author: "Professional Team", rating: 5, comment: "Everyone from the sales rep to the installers was professional and friendly." },
          { author: "Kitchen Blinds", rating: 5, comment: "The aluminium Venetian blinds are perfect for my kitchen. Easy to clean." },
          { author: "Living Room", rating: 5, comment: "The Roman blinds add a touch of elegance to my living room. I love them." },
          { author: "Highly Recommend", rating: 5, comment: "I would highly recommend Blind Ambition. Great products and great service." }
        ],
        photos: ["https://picsum.photos/seed/blinds1/600/400"],
        avatarSeed: "blind-ambition-logo"
      }
    ],
    default: [],
};

export const getProfessionalById = (id: string) => {
    for (const category in allProfessionals) {
        if (Object.prototype.hasOwnProperty.call(allProfessionals, category)) {
            const professionalsInCategory = (allProfessionals as any)[category];
            const found = professionalsInCategory.find((pro: any) => pro.id === id);
            if (found) {
                return found;
            }
        }
    }
    return null;
};
