

type Professional = {
  id: string;
  name: string;
  location: string;
  description: string;
  rating: number;
  reviews: number;
  avatarSeed: string;
  serviceCategory: string;
  serviceLocations?: string[];
  tags?: string[];
  isProVerified?: boolean;
  yearsInBusiness?: number;
  employees?: number;
  address?: string;
  photos?: string[];
  businessHours?: string;
  services?: string[];
  otherServices?: string[];
  reviewData?: {
    author: string;
    phone?: string;
    rating: number;
    comment: string;
  }[];
  isDemo: boolean;
  priorityRank: number;
};

type ProfessionalsByCategory = {
  [key: string]: Professional[];
};

export const allProfessionals: ProfessionalsByCategory = {
    "handymen": [
      { "id": "handy-001", "name": "FixAll Sandton Handyman", "location": "Sandton, Johannesburg", "description": "Reliable handyman services for minor repairs, installations, and home maintenance across Sandton, Randburg, and nearby suburbs.", "rating": 4.9, "reviews": 250, "avatarSeed": "fixall-sandton-handyman-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 5, "services": ["Minor Repairs", "Installations", "Home Maintenance"], "otherServices": ["Picture Hanging", "Furniture Assembly"], "reviewData": [{"author": "Mrs. Green", "rating": 5, "comment": "A true lifesaver! He fixed a dozen small things around my house in one afternoon. Punctual and professional."}] },
      { "id": "handy-002", "name": "Khaya Handy Services PTA", "location": "Pretoria", "description": "Professional handyman solutions for homes and offices in Pretoria, offering quality workmanship and quick turnaround.", "rating": 4.8, "reviews": 190, "avatarSeed": "khaya-handy-services-pta-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 7, "services": ["Home & Office Repairs", "Property Maintenance", "General Handyman Work"], "otherServices": ["Tiling Repairs", "Painting Touch-ups"], "reviewData": [{"author": "Pretoria Business Suites", "rating": 5, "comment": "Khaya Handy Services is our go-to for all office maintenance. They are reliable and the work is always top-notch."}] },
      { "id": "handy-003", "name": "SmartFix Midrand", "location": "Midrand", "description": "Affordable handyman services covering Midrand and Kempton Park, from general repairs to property maintenance.", "rating": 4.7, "reviews": 210, "avatarSeed": "smartfix-midrand-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 6, "services": ["General Repairs", "Property Maintenance", "Installation Services"], "otherServices": ["Gutter Cleaning", "Minor Plumbing"], "reviewData": [{"author": "T. Pillay", "rating": 5, "comment": "Great value for money and a very friendly service. They fixed my leaking tap and hung some shelves perfectly."}] },
      { "id": "handy-004", "name": "UrbanHandy Gauteng", "location": "Gauteng", "description": "Skilled handyman services across Gauteng, including Boksburg and surrounding residential areas.", "rating": 4.8, "reviews": 230, "avatarSeed": "urbanhandy-gauteng-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 10, "services": ["Multi-skilled Handyman", "Home Repair Services", "Installation Work"], "otherServices": ["Drywall Patching", "Door Adjustments"], "reviewData": [{"author": "Boksburg Homeowner", "rating": 5, "comment": "It's so convenient to have one person who can handle so many different types of jobs. Very skilled and professional."}] },
      { "id": "handy-005", "name": "ProTask Handymen", "location": "Gauteng", "description": "Flexible handyman support for households and small businesses throughout Gauteng.", "rating": 4.7, "reviews": 180, "avatarSeed": "protask-handymen-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 8, "services": ["Small Job Specialist", "Business Maintenance", "Home Repair Tasks"], "otherServices": ["Fixture Replacement", "Assembly Services"], "reviewData": [{"author": "Local Cafe Owner", "rating": 5, "comment": "They are perfect for all the small maintenance tasks around my shop. Always reliable and professional."}] }
    ],
    "high-pressure-cleaning": [
      { "id": "hpc-001", "name": "AquaBlast Sandton", "location": "Sandton", "description": "Professional high-pressure cleaning for driveways, roofs, and walls in Sandton and Randburg.", "rating": 4.9, "reviews": 150, "avatarSeed": "aquablast-sandton-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 10, "services": ["Driveway Cleaning", "Roof Cleaning", "Wall Cleaning"], "otherServices": ["Patio Cleaning", "Oil Stain Removal"], "reviewData": [{"author": "Fourways Gardens Estate", "rating": 5, "comment": "They do an amazing job of keeping our communal driveways and walls clean. Very reliable."}] },
      { "id": "hpc-002", "name": "Vuma Pressure Clean PTA", "location": "Pretoria", "description": "Reliable pressure cleaning services for driveways, walls, and roofs in Pretoria.", "rating": 4.8, "reviews": 180, "avatarSeed": "vuma-pressure-clean-pta-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 12, "services": ["Residential Pressure Cleaning", "Commercial Cleaning", "Roof Cleaning"], "otherServices": ["Paving Sealing", "Graffiti Removal"], "reviewData": [{"author": "C. van der Walt", "rating": 5, "comment": "My roof looks brand new again! Excellent service and very professional team."}] },
      { "id": "hpc-003", "name": "SkoonForce Midrand", "location": "Midrand", "description": "Affordable high-pressure cleaning for residential and commercial properties in Midrand.", "rating": 4.7, "reviews": 130, "avatarSeed": "skoonforce-midrand-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 8, "services": ["Driveway & Paving Cleaning", "Wall Cleaning", "Pre-painting Cleaning"], "otherServices": ["Gutter Cleaning", "General Maintenance"], "reviewData": [{"author": "K. Pillay", "rating": 5, "comment": "Great value for money. They did a fantastic job cleaning my driveway and boundary walls."}] },
      { "id": "hpc-004", "name": "ProJet Wash Gauteng", "location": "Gauteng", "description": "Powerful pressure washing services serving Boksburg, Sandton, and wider Gauteng areas.", "rating": 4.8, "reviews": 200, "avatarSeed": "projet-wash-gauteng-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Industrial Cleaning", "Commercial Fleet Washing", "Building Exteriors"], "otherServices": ["Heavy-duty Degreasing", "Factory Floor Cleaning"], "reviewData": [{"author": "East Rand Industrial", "rating": 5, "comment": "They have the heavy-duty equipment needed for our factory. A very professional and efficient service."}] },
      { "id": "hpc-005", "name": "Tito Power Wash", "location": "Gauteng", "description": "Trusted pressure cleaning specialists restoring outdoor surfaces across Gauteng.", "rating": 4.9, "reviews": 160, "avatarSeed": "tito-power-wash-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 7, "services": ["Residential High-Pressure Cleaning", "Roof Cleaning", "Paving Cleaning"], "otherServices": ["Deck Cleaning", "Fence Cleaning"], "reviewData": [{"author": "J. Botha", "rating": 5, "comment": "Tito and his team are fantastic. They are friendly, professional, and do an amazing job."}] }
    ],
    "home-improvements": [
      { "id": "imp-001", "name": "BuildRight Sandton", "location": "Sandton", "description": "Quality home improvement and renovation services for properties in Sandton and Randburg.", "rating": 4.9, "reviews": 180, "avatarSeed": "buildright-sandton-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 20, "services": ["Home Renovations", "Kitchen & Bathroom Remodeling", "Building Alterations"], "otherServices": ["Tiling", "Painting"], "reviewData": [{"author": "The Miller Family", "rating": 5, "comment": "BuildRight handled our full home renovation, and we couldn't be happier. Professional from start to finish."}] },
      { "id": "imp-002", "name": "Khaya Improve PTA", "location": "Pretoria", "description": "Affordable home upgrades and maintenance services for Pretoria households.", "rating": 4.8, "reviews": 220, "avatarSeed": "khaya-improve-pta-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 15, "services": ["Home Maintenance", "Renovations", "Painting & Waterproofing"], "otherServices": ["Tiling", "Paving Repairs"], "reviewData": [{"author": "A. Grobler", "rating": 5, "comment": "Reliable and well-priced. They have helped us with several projects around the house."}] },
      { "id": "imp-003", "name": "SmartHaus Midrand", "location": "Midrand", "description": "Modern home improvement solutions for Midrand and Kempton Park residential properties.", "rating": 4.7, "reviews": 150, "avatarSeed": "smarthaus-midrand-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 10, "services": ["Modern Renovations", "Smart Home Integration", "Kitchen & Bath Upgrades"], "otherServices": ["Custom Cabinetry", "Energy-efficient Solutions"], "reviewData": [{"author": "D. Chen", "rating": 5, "comment": "They had great ideas for modernizing our home. The project was managed well and finished on time."}] },
      { "id": "imp-004", "name": "Mzansi HomeWorks", "location": "Gauteng", "description": "Reliable home improvement specialists serving residential clients in Gauteng.", "rating": 4.8, "reviews": 250, "avatarSeed": "mzansi-homeworks-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 25, "services": ["General Home Improvements", "Renovations", "Maintenance Services"], "otherServices": ["Roof Repairs", "Ceiling Installations"], "reviewData": [{"author": "S. Van Wyk", "rating": 5, "comment": "A great team that can handle a wide variety of work. We've used them for painting, tiling, and roof repairs."}] },
      { "id": "imp-005", "name": "ProFix Living", "location": "Gauteng", "description": "End-to-end home improvement and repair solutions for Gauteng homes.", "rating": 4.7, "reviews": 190, "avatarSeed": "profix-living-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 12, "services": ["Home Improvement Projects", "Repair Services", "Renovation Management"], "otherServices": ["Handyman Services", "Installations"], "reviewData": [{"author": "P. Govender", "rating": 5, "comment": "Very professional and organized. They managed our bathroom renovation project smoothly and kept us updated."}] }
    ],
    "interior-designing": [
      { "id": "design-001", "name": "UrbanNest Sandton Interiors", "location": "Sandton", "description": "Stylish and functional interior design solutions for Sandton homes and offices.", "rating": 4.9, "reviews": 90, "avatarSeed": "urbannest-sandton-interiors-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 6, "services": ["Residential Interior Design", "Office Design", "Space Planning"], "otherServices": ["Furniture Sourcing", "Decor Styling"], "reviewData": [{"author": "Luxe Apartments Sandton", "rating": 5, "comment": "They have a fantastic eye for modern, luxurious design. Transformed our show unit."}] },
      { "id": "design-002", "name": "Zola Space Design PTA", "location": "Pretoria", "description": "Creative interior design concepts tailored for Pretoria clients.", "rating": 4.8, "reviews": 110, "avatarSeed": "zola-space-design-pta-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 4, "services": ["Interior Design & Decor", "Home Staging", "Colour Consultation"], "otherServices": ["Custom Furniture Design", "Art Curation"], "reviewData": [{"author": "The Mokoena Family", "rating": 5, "comment": "Zola listened to our needs and created a beautiful, family-friendly space that we love."}] },
      { "id": "design-003", "name": "LuxeKhaya Midrand", "location": "Midrand", "description": "Modern interior styling services for residential and commercial spaces in Midrand.", "rating": 4.8, "reviews": 85, "avatarSeed": "luxekhaya-midrand-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 3, "services": ["Interior Styling", "Commercial Space Design", "Modern Aesthetics"], "otherServices": ["Lighting Design", "Soft Furnishings"], "reviewData": [{"author": "Tech Park Midrand", "rating": 5, "comment": "They designed our new office reception and boardroom. It's modern, professional, and impressive."}] },
      { "id": "design-004", "name": "Elegant Room Gauteng", "location": "Gauteng", "description": "Professional interior design services serving clients across Gauteng.", "rating": 4.7, "reviews": 120, "avatarSeed": "elegant-room-gauteng-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 7, "services": ["Full-Service Interior Design", "Home Decor", "Project Management"], "otherServices": ["Space Optimization", "Custom Curtains & Blinds"], "reviewData": [{"author": "J. van Rensburg", "rating": 5, "comment": "Their team made the whole process so easy. From concept to completion, everything was handled professionally."}] },
      { "id": "design-005", "name": "Forma Interior Studio", "location": "Gauteng", "description": "Contemporary interior design solutions focused on comfort and aesthetics.", "rating": 4.9, "reviews": 75, "avatarSeed": "forma-interior-studio-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 4, "employees": 2, "services": ["Contemporary Design", "Minimalist Interiors", "Design Consultation"], "otherServices": ["Furniture Layout", "Material Selection"], "reviewData": [{"author": "City Loft Owner", "rating": 5, "comment": "Love their minimalist approach. They created a space that is both stylish and incredibly functional."}] }
    ],
    "kitchen-renovations": [
      { "id": "kitch-001", "name": "PrimeCook Sandton Kitchens", "location": "Sandton, Johannesburg", "description": "Custom kitchen renovations delivering modern finishes in Sandton and Randburg.", "rating": 4.9, "reviews": 120, "avatarSeed": "primecook-sandton-kitchens-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 12, "services": ["Custom Kitchens", "Modern Cabinetry", "Quartz & Granite Countertops"], "otherServices": ["Appliance Integration", "Lighting Design"], "reviewData": [{"author": "B. Taylor", "rating": 5, "comment": "Our dream kitchen is now a reality. The quality of the cabinets and the attention to detail is outstanding."}] },
      { "id": "kitch-002", "name": "Khaya Kitchen Studio PTA", "location": "Pretoria", "description": "Professional kitchen remodeling services for Pretoria homes.", "rating": 4.8, "reviews": 150, "avatarSeed": "khaya-kitchen-studio-pta-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 10, "services": ["Kitchen Remodeling", "Cabinet Refacing", "Countertop Installation"], "otherServices": ["Tiling & Splashbacks", "Plumbing for Kitchens"], "reviewData": [{"author": "Mrs. du Preez", "rating": 5, "comment": "They gave our old kitchen a complete facelift. It looks amazing and was surprisingly affordable."}] },
      { "id": "kitch-003", "name": "Elite Cabinetry Midrand", "location": "Midrand", "description": "High-quality kitchen cabinetry and renovation solutions in Midrand and Kempton Park.", "rating": 4.8, "reviews": 110, "avatarSeed": "elite-cabinetry-midrand-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 15, "services": ["Custom Cabinetry", "Full Kitchen Renovations", "Design & Layout"], "otherServices": ["Bar & Entertainment Areas", "Office Kitchenettes"], "reviewData": [{"author": "Waterfall Estate Home", "rating": 5, "comment": "The craftsmanship of their cabinets is second to none. A truly elite service."}] },
      { "id": "kitch-004", "name": "ModernTaste Gauteng", "location": "Gauteng", "description": "Stylish kitchen renovation services for households across Gauteng.", "rating": 4.7, "reviews": 180, "avatarSeed": "moderntaste-gauteng-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 14, "services": ["Modern Kitchen Design", "Renovations", "Appliance Sourcing"], "otherServices": ["Open-plan living conversions", "Smart kitchen features"], "reviewData": [{"author": "The Johnson Family", "rating": 5, "comment": "We love our new open-plan kitchen. ModernTaste managed the entire project, including breaking down walls."}] },
      { "id": "kitch-005", "name": "Saffron Kitchen Co", "location": "Gauteng", "description": "Functional and elegant kitchen upgrades tailored to each client’s needs.", "rating": 4.9, "reviews": 95, "avatarSeed": "saffron-kitchen-co-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 8, "services": ["Kitchen Upgrades", "Functional Design", "Bespoke Solutions"], "otherServices": ["Pantry Organization", "Custom Storage"], "reviewData": [{"author": "G. Patel", "rating": 5, "comment": "They really understood how I use my kitchen and designed a space that is both beautiful and incredibly practical."}] }
    ],
    "laminate-flooring": [
      { "id": "lam-001", "name": "FloorCraft Sandton", "location": "Sandton", "description": "Professional laminate flooring installations for homes and offices in Sandton and Randburg.", "rating": 4.8, "reviews": 140, "avatarSeed": "floorcraft-sandton-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 10, "services": ["Laminate Flooring Installation", "Skirting Installation", "Floor Leveling"], "otherServices": ["Old Floor Removal", "Vinyl Flooring"], "reviewData": [{"author": "Sandton Corporate Offices", "rating": 5, "comment": "Fast, neat, and professional installation for our new office floor. It looks fantastic."}] },
      { "id": "lam-002", "name": "SkoonStep Flooring PTA", "location": "Pretoria", "description": "Durable laminate flooring solutions across Pretoria residential properties.", "rating": 4.7, "reviews": 160, "avatarSeed": "skoonstep-flooring-pta-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 8, "services": ["Residential Laminate Flooring", "Wide Range of Styles", "Staircase Cladding"], "otherServices": ["Floor Maintenance", "Repairs"], "reviewData": [{"author": "The Botha Family", "rating": 5, "comment": "They have a huge range to choose from. The installation was quick and the team was very professional."}] },
      { "id": "lam-003", "name": "TimberLine Midrand", "location": "Midrand", "description": "Affordable laminate flooring supply and installation in Midrand and Kempton Park.", "rating": 4.7, "reviews": 125, "avatarSeed": "timberline-midrand-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 7, "services": ["Laminate Flooring Supply", "Professional Installation", "Budget-friendly options"], "otherServices": ["Vinyl Plank Flooring", "Engineered Wood"], "reviewData": [{"author": "Midrand First-time Homebuyer", "rating": 5, "comment": "Great prices and excellent service. They helped me choose the right floor for my budget."}] },
      { "id": "lam-004", "name": "UrbanPlank Gauteng", "location": "Gauteng", "description": "Modern laminate flooring designs for Gauteng homes.", "rating": 4.8, "reviews": 190, "avatarSeed": "urbanplank-gauteng-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 12, "services": ["Modern Laminate Designs", "Herringbone Patterns", "Wide Plank Flooring"], "otherServices": ["Custom Transitions", "Soundproofing Underlay"], "reviewData": [{"author": "Loft Apartment JHB", "rating": 5, "comment": "If you're looking for something modern and different, this is the company. My herringbone floor is stunning."}] },
      { "id": "lam-005", "name": "SolidStep Floors", "location": "Gauteng", "description": "Quality laminate flooring installations built for long-lasting performance.", "rating": 4.9, "reviews": 110, "avatarSeed": "solidstep-floors-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 9, "services": ["High-traffic Laminate", "Commercial Installations", "Quality Guarantee"], "otherServices": ["Water-resistant options", "Sub-floor preparation"], "reviewData": [{"author": "Boksburg Retail Store", "rating": 5, "comment": "We needed something durable for our store, and they delivered. The floor is tough and still looks new after months of heavy foot traffic."}] }
    ],
    "landscaping": [
      { "id": "land-001", "name": "GreenLeaf Sandton Landscapes", "location": "Sandton, Johannesburg", "description": "Professional landscaping services for homes and offices in Sandton and Randburg.", "rating": 4.9, "reviews": 120, "avatarSeed": "greenleaf-sandton-landscapes-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Garden Design", "Lawn Care", "Regular Maintenance"], "otherServices": ["Irrigation Systems", "Tree Pruning"], "reviewData": [{ "author": "J. Smit", "rating": 5, "comment": "Our garden has never looked better! The team is professional and knowledgeable." }] },
      { "id": "land-002", "name": "Vusi Landscapes PTA", "location": "Pretoria", "description": "Garden design and landscaping solutions throughout Pretoria and surrounding suburbs.", "rating": 4.8, "reviews": 95, "avatarSeed": "vuma-landscapes-pta-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 12, "services": ["Garden Design", "Commercial Landscaping", "Residential Maintenance"], "otherServices": ["Water Features", "Paving"], "reviewData": [{ "author": "Mrs. van der Merwe", "rating": 5, "comment": "Vuma transformed our tired garden into a beautiful, low-maintenance space." }] },
      { "id": "land-003", "name": "Khu Garden Midrand", "location": "Midrand", "description": "Affordable landscaping and garden maintenance in Midrand and Kempton Park.", "rating": 4.7, "reviews": 110, "avatarSeed": "khula-garden-midrand-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 8, "services": ["Garden Maintenance", "Lawn Mowing", "Planting Services"], "otherServices": ["Weed Control", "Fertilizing"], "reviewData": [{ "author": "T. Khumalo", "rating": 5, "comment": "Reliable and affordable. My garden is always neat and tidy." }] },
      { "id": "land-004", "name": "EdenScape Gauteng", "location": "Gauteng", "description": "Complete outdoor landscaping solutions across Gauteng, including Boksburg.", "rating": 4.8, "reviews": 150, "avatarSeed": "edenscape-gauteng-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 20, "services": ["Full Garden Makeovers", "Soft Landscaping", "Commercial Maintenance"], "otherServices": ["Irrigation Installation", "Hardscaping"], "reviewData": [{ "author": "Boksburg Business Park", "rating": 5, "comment": "EdenScape manages all our commercial properties' gardens. They are professional and reliable." }] },
      { "id": "land-005", "name": "TerraGrow Projects", "location": "Gauteng", "description": "Custom landscape design and garden improvements for residential properties.", "rating": 4.7, "reviews": 80, "avatarSeed": "terragrow-projects-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 10, "services": ["Custom Landscape Design", "Garden Improvements", "Project Management"], "otherServices": ["Outdoor Lighting", "Decking"], "reviewData": [{ "author": "L. Naidoo", "rating": 5, "comment": "They had fantastic ideas for my small garden space and executed the project perfectly." }] }
    ],
    "roofer": [
        { "id": "roof-001", "name": "Bravo Projects", "location": "Randburg", "description": "Reliable and experienced roofing contractors for {service} repairs, waterproofing, and new installations. No job is too big or small.", "rating": 4.9, "reviews": 185, "isProVerified": true, "avatarSeed": "roofer-image", "serviceCategory": "roofer", "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 20, "services": ["Roof Leak Repairs", "Waterproofing", "New Roof Installations"], "otherServices": ["Gutter Cleaning", "Roof Painting"], "reviewData": [{"author": "T. Molefe", "rating": 5, "comment": "They found and fixed a persistent leak that two other companies couldn't. Very knowledgeable and professional."}] }
    ]
};

export const getProfessionalById = (id: string): Professional | null => {
    for (const category in allProfessionals) {
        if (Object.prototype.hasOwnProperty.call(allProfessionals, category)) {
            const professionalsInCategory = allProfessionals[category];
            const found = professionalsInCategory.find((pro: Professional) => pro.id === id);
            if (found) {
                return found;
            }
        }
    }
    return null;
};
