

type Professional = {
  id: string;
  name: string;
  location: string;
  description: string;
  rating: number;
  reviews: number;
  avatarSeed: string;
  serviceCategory: string;
  serviceLocations?: string[];
  tags?: string[];
  isProVerified?: boolean;
  yearsInBusiness?: number;
  employees?: number;
  address?: string;
  photos?: string[];
  businessHours?: string;
  services?: string[];
  otherServices?: string[];
  reviewData?: {
    author: string;
    phone?: string;
    rating: number;
    comment: string;
  }[];
  isDemo: boolean;
  priorityRank: number;
};

type ProfessionalsByCategory = {
  [key: string]: Professional[];
};

export const allProfessionals: ProfessionalsByCategory = {
    "handymen": [
      { "id": "handy-001", "name": "FixAll Sandton Handyman", "location": "Sandton, Johannesburg", "description": "Reliable handyman services for minor repairs, installations, and home maintenance across Sandton, Randburg, and nearby suburbs.", "rating": 4.9, "reviews": 250, "avatarSeed": "fixall-sandton-handyman-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 5, "services": ["Minor Repairs", "Installations", "Home Maintenance"], "otherServices": ["Picture Hanging", "Furniture Assembly"], "reviewData": [{"author": "Mrs. Green", "rating": 5, "comment": "A true lifesaver! He fixed a dozen small things around my house in one afternoon. Punctual and professional."}] },
      { "id": "handy-002", "name": "Khaya Handy Services PTA", "location": "Pretoria", "description": "Professional handyman solutions for homes and offices in Pretoria, offering quality workmanship and quick turnaround.", "rating": 4.8, "reviews": 190, "avatarSeed": "khaya-handy-services-pta-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 7, "services": ["Home & Office Repairs", "Property Maintenance", "General Handyman Work"], "otherServices": ["Tiling Repairs", "Painting Touch-ups"], "reviewData": [{"author": "Pretoria Business Suites", "rating": 5, "comment": "Khaya Handy Services is our go-to for all office maintenance. They are reliable and the work is always top-notch."}] },
      { "id": "handy-003", "name": "SmartFix Midrand", "location": "Midrand", "description": "Affordable handyman services covering Midrand and Kempton Park, from general repairs to property maintenance.", "rating": 4.7, "reviews": 210, "avatarSeed": "smartfix-midrand-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 6, "services": ["General Repairs", "Property Maintenance", "Installation Services"], "otherServices": ["Gutter Cleaning", "Minor Plumbing"], "reviewData": [{"author": "T. Pillay", "rating": 5, "comment": "Great value for money and a very friendly service. They fixed my leaking tap and hung some shelves perfectly."}] },
      { "id": "handy-004", "name": "UrbanHandy Gauteng", "location": "Gauteng", "description": "Skilled handyman services across Gauteng, including Boksburg and surrounding residential areas.", "rating": 4.8, "reviews": 230, "avatarSeed": "urbanhandy-gauteng-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 10, "services": ["Multi-skilled Handyman", "Home Repair Services", "Installation Work"], "otherServices": ["Drywall Patching", "Door Adjustments"], "reviewData": [{"author": "Boksburg Homeowner", "rating": 5, "comment": "It's so convenient to have one person who can handle so many different types of jobs. Very skilled and professional."}] },
      { "id": "handy-005", "name": "ProTask Handymen", "location": "Gauteng", "description": "Flexible handyman support for households and small businesses throughout Gauteng.", "rating": 4.7, "reviews": 180, "avatarSeed": "protask-handymen-logo", "serviceCategory": "handymen", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 8, "services": ["Small Job Specialist", "Business Maintenance", "Home Repair Tasks"], "otherServices": ["Fixture Replacement", "Assembly Services"], "reviewData": [{"author": "Local Cafe Owner", "rating": 5, "comment": "They are perfect for all the small maintenance tasks around my shop. Always reliable and professional."}] }
    ],
    "high-pressure-cleaning": [
      { "id": "hpc-001", "name": "AquaBlast Sandton", "location": "Sandton, Johannesburg", "description": "Professional high-pressure cleaning for driveways, roofs, and walls in Sandton and Randburg.", "rating": 4.9, "reviews": 150, "avatarSeed": "aquablast-sandton-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 10, "services": ["Driveway Cleaning", "Roof Cleaning", "Wall Cleaning"], "otherServices": ["Patio Cleaning", "Oil Stain Removal"], "reviewData": [{"author": "Fourways Gardens Estate", "rating": 5, "comment": "They do an amazing job of keeping our communal driveways and walls clean. Very reliable."}] },
      { "id": "hpc-002", "name": "Vuma Pressure Clean PTA", "location": "Pretoria", "description": "Reliable pressure cleaning services for residential and commercial properties across Pretoria.", "rating": 4.8, "reviews": 180, "avatarSeed": "vuma-pressure-clean-pta-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 12, "services": ["Residential Pressure Cleaning", "Commercial Cleaning", "Roof Cleaning"], "otherServices": ["Paving Sealing", "Graffiti Removal"], "reviewData": [{"author": "C. van der Walt", "rating": 5, "comment": "My roof looks brand new again! Excellent service and very professional team."}] },
      { "id": "hpc-003", "name": "SkoonForce Midrand", "location": "Midrand", "description": "Affordable high-pressure cleaning solutions in Midrand and Kempton Park, delivering spotless results.", "rating": 4.7, "reviews": 130, "avatarSeed": "skoonforce-midrand-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 8, "services": ["Driveway & Paving Cleaning", "Wall Cleaning", "Pre-painting Cleaning"], "otherServices": ["Gutter Cleaning", "General Maintenance"], "reviewData": [{"author": "K. Pillay", "rating": 5, "comment": "Great value for money. They did a fantastic job cleaning my driveway and boundary walls."}] },
      { "id": "hpc-004", "name": "ProJet Wash Gauteng", "location": "Gauteng", "description": "Powerful pressure washing services serving Boksburg, Sandton, and wider Gauteng areas.", "rating": 4.8, "reviews": 200, "avatarSeed": "projet-wash-gauteng-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Industrial Cleaning", "Commercial Fleet Washing", "Building Exteriors"], "otherServices": ["Heavy-duty Degreasing", "Factory Floor Cleaning"], "reviewData": [{"author": "East Rand Industrial", "rating": 5, "comment": "They have the heavy-duty equipment needed for our factory. A very professional and efficient service."}] },
      { "id": "hpc-005", "name": "Tito Power Wash", "location": "Gauteng", "description": "Trusted pressure cleaning specialists restoring outdoor surfaces across Gauteng.", "rating": 4.9, "reviews": 160, "avatarSeed": "tito-power-wash-logo", "serviceCategory": "high-pressure-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 7, "services": ["Residential High-Pressure Cleaning", "Roof Cleaning", "Paving Cleaning"], "otherServices": ["Deck Cleaning", "Fence Cleaning"], "reviewData": [{"author": "J. Botha", "rating": 5, "comment": "Tito and his team are fantastic. They are friendly, professional, and do an amazing job."}] }
    ],
    "home-improvements": [
      { "id": "imp-001", "name": "BuildRight Sandton", "location": "Sandton, Johannesburg", "description": "Quality home improvement and renovation services for properties in Sandton and Randburg.", "rating": 4.9, "reviews": 180, "avatarSeed": "buildright-sandton-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 20, "services": ["Home Renovations", "Kitchen & Bathroom Remodeling", "Building Alterations"], "otherServices": ["Tiling", "Painting"], "reviewData": [{"author": "The Miller Family", "rating": 5, "comment": "BuildRight handled our full home renovation, and we couldn't be happier. Professional from start to finish."}] },
      { "id": "imp-002", "name": "Khaya Improve PTA", "location": "Pretoria", "description": "Affordable home upgrades and maintenance services for Pretoria households.", "rating": 4.8, "reviews": 220, "avatarSeed": "khaya-improve-pta-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 15, "services": ["Home Maintenance", "Renovations", "Painting & Waterproofing"], "otherServices": ["Tiling", "Paving Repairs"], "reviewData": [{"author": "A. Grobler", "rating": 5, "comment": "Reliable and well-priced. They have helped us with several projects around the house."}] },
      { "id": "imp-003", "name": "SmartHaus Midrand", "location": "Midrand", "description": "Modern home improvement solutions for Midrand and Kempton Park residential properties.", "rating": 4.7, "reviews": 150, "avatarSeed": "smarthaus-midrand-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 10, "services": ["Modern Renovations", "Smart Home Integration", "Kitchen & Bath Upgrades"], "otherServices": ["Custom Cabinetry", "Energy-efficient Solutions"], "reviewData": [{"author": "D. Chen", "rating": 5, "comment": "They had great ideas for modernizing our home. The project was managed well and finished on time."}] },
      { "id": "imp-004", "name": "Mzansi HomeWorks", "location": "Gauteng", "description": "Reliable home improvement specialists serving homes across Gauteng.", "rating": 4.8, "reviews": 250, "avatarSeed": "mzansi-homeworks-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 25, "services": ["General Home Improvements", "Renovations", "Maintenance Services"], "otherServices": ["Roof Repairs", "Ceiling Installations"], "reviewData": [{"author": "S. Van Wyk", "rating": 5, "comment": "A great team that can handle a wide variety of work. We've used them for painting, tiling, and roof repairs."}] },
      { "id": "imp-005", "name": "ProFix Living", "location": "Gauteng", "description": "Professional home improvement services tailored to client needs across Gauteng.", "rating": 4.7, "reviews": 190, "avatarSeed": "profix-living-logo", "serviceCategory": "home-improvements", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 12, "services": ["Home Improvement Projects", "Repair Services", "Renovation Management"], "otherServices": ["Handyman Services", "Installations"], "reviewData": [{"author": "P. Govender", "rating": 5, "comment": "Very professional and organized. They managed our bathroom renovation project smoothly and kept us updated."}] }
    ],
    "interior-designing": [
      { "id": "design-001", "name": "UrbanNest Sandton Interiors", "location": "Sandton, Johannesburg", "description": "Stylish interior design solutions for homes and offices in Sandton and Randburg.", "rating": 4.9, "reviews": 90, "avatarSeed": "urbannest-sandton-interiors-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 6, "services": ["Residential Interior Design", "Office Design", "Space Planning"], "otherServices": ["Furniture Sourcing", "Decor Styling"], "reviewData": [{"author": "Luxe Apartments Sandton", "rating": 5, "comment": "They have a fantastic eye for modern, luxurious design. Transformed our show unit."}] },
      { "id": "design-002", "name": "Zola Space Design PTA", "location": "Pretoria", "description": "Creative and functional interior design concepts tailored for Pretoria clients.", "rating": 4.8, "reviews": 110, "avatarSeed": "zola-space-design-pta-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 4, "services": ["Interior Design & Decor", "Home Staging", "Colour Consultation"], "otherServices": ["Custom Furniture Design", "Art Curation"], "reviewData": [{"author": "The Mokoena Family", "rating": 5, "comment": "Zola listened to our needs and created a beautiful, family-friendly space that we love."}] },
      { "id": "design-003", "name": "LuxeKhaya Midrand", "location": "Midrand", "description": "Modern interior styling services for residential and commercial spaces in Midrand and Kempton Park.", "rating": 4.8, "reviews": 85, "avatarSeed": "luxekhaya-midrand-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 3, "services": ["Interior Styling", "Commercial Space Design", "Modern Aesthetics"], "otherServices": ["Lighting Design", "Soft Furnishings"], "reviewData": [{"author": "Tech Park Midrand", "rating": 5, "comment": "They designed our new office reception and boardroom. It's modern, professional, and impressive."}] },
      { "id": "design-004", "name": "Elegant Room Gauteng", "location": "Gauteng", "description": "Professional interior design services serving clients across Gauteng.", "rating": 4.7, "reviews": 120, "avatarSeed": "elegant-room-gauteng-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 7, "services": ["Full-Service Interior Design", "Home Decor", "Project Management"], "otherServices": ["Space Optimization", "Custom Curtains & Blinds"], "reviewData": [{"author": "J. van Rensburg", "rating": 5, "comment": "Their team made the whole process so easy. From concept to completion, everything was handled professionally."}] },
      { "id": "design-005", "name": "Forma Interior Studio", "location": "Gauteng", "description": "Contemporary interior design solutions focused on comfort and aesthetics.", "rating": 4.9, "reviews": 75, "avatarSeed": "forma-interior-studio-logo", "serviceCategory": "interior-designing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 4, "employees": 2, "services": ["Contemporary Design", "Minimalist Interiors", "Design Consultation"], "otherServices": ["Furniture Layout", "Material Selection"], "reviewData": [{"author": "City Loft Owner", "rating": 5, "comment": "Love their minimalist approach. They created a space that is both stylish and incredibly functional."}] }
    ],
    "kitchen-renovations": [
      { "id": "kitch-001", "name": "PrimeCook Sandton Kitchens", "location": "Sandton, Johannesburg", "description": "Custom kitchen renovations delivering modern finishes in Sandton and Randburg.", "rating": 4.9, "reviews": 120, "avatarSeed": "primecook-sandton-kitchens-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 12, "services": ["Custom Kitchens", "Modern Cabinetry", "Quartz & Granite Countertops"], "otherServices": ["Appliance Integration", "Lighting Design"], "reviewData": [{"author": "B. Taylor", "rating": 5, "comment": "Our dream kitchen is now a reality. The quality of the cabinets and the attention to detail is outstanding."}] },
      { "id": "kitch-002", "name": "Khaya Kitchen Studio PTA", "location": "Pretoria", "description": "Professional kitchen remodeling services for Pretoria homes.", "rating": 4.8, "reviews": 150, "avatarSeed": "khaya-kitchen-studio-pta-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 10, "services": ["Kitchen Remodeling", "Cabinet Refacing", "Countertop Installation"], "otherServices": ["Tiling & Splashbacks", "Plumbing for Kitchens"], "reviewData": [{"author": "Mrs. du Preez", "rating": 5, "comment": "They gave our old kitchen a complete facelift. It looks amazing and was surprisingly affordable."}] },
      { "id": "kitch-003", "name": "Elite Cabinetry Midrand", "location": "Midrand", "description": "High-quality kitchen cabinetry and renovation solutions in Midrand and Kempton Park.", "rating": 4.8, "reviews": 110, "avatarSeed": "elite-cabinetry-midrand-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 15, "services": ["Custom Cabinetry", "Full Kitchen Renovations", "Design & Layout"], "otherServices": ["Bar & Entertainment Areas", "Office Kitchenettes"], "reviewData": [{"author": "Waterfall Estate Home", "rating": 5, "comment": "The craftsmanship of their cabinets is second to none. A truly elite service."}] },
      { "id": "kitch-004", "name": "ModernTaste Gauteng", "location": "Gauteng", "description": "Stylish kitchen renovation solutions for households across Gauteng.", "rating": 4.7, "reviews": 180, "avatarSeed": "moderntaste-gauteng-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 14, "services": ["Modern Kitchen Design", "Renovations", "Appliance Sourcing"], "otherServices": ["Open-plan living conversions", "Smart kitchen features"], "reviewData": [{"author": "The Johnson Family", "rating": 5, "comment": "We love our new open-plan kitchen. ModernTaste managed the entire project, including breaking down walls."}] },
      { "id": "kitch-005", "name": "Saffron Kitchen Co", "location": "Gauteng", "description": "Functional and elegant kitchen upgrades tailored to each client’s needs.", "rating": 4.9, "reviews": 95, "avatarSeed": "saffron-kitchen-co-logo", "serviceCategory": "kitchen-renovations", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 8, "services": ["Kitchen Upgrades", "Functional Design", "Bespoke Solutions"], "otherServices": ["Pantry Organization", "Custom Storage"], "reviewData": [{"author": "G. Patel", "rating": 5, "comment": "They really understood how I use my kitchen and designed a space that is both beautiful and incredibly practical."}] }
    ],
    "laminate-flooring": [
      { "id": "lam-001", "name": "FloorCraft Sandton", "location": "Sandton", "description": "Professional laminate flooring installations for homes and offices in Sandton and Randburg.", "rating": 4.8, "reviews": 140, "avatarSeed": "floorcraft-sandton-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 10, "services": ["Laminate Flooring Installation", "Skirting Installation", "Floor Leveling"], "otherServices": ["Old Floor Removal", "Vinyl Flooring"], "reviewData": [{"author": "Sandton Corporate Offices", "rating": 5, "comment": "Fast, neat, and professional installation for our new office floor. It looks fantastic."}] },
      { "id": "lam-002", "name": "SkoonStep Flooring PTA", "location": "Pretoria", "description": "Durable laminate flooring solutions across Pretoria residential properties.", "rating": 4.7, "reviews": 160, "avatarSeed": "skoonstep-flooring-pta-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 8, "services": ["Residential Laminate Flooring", "Wide Range of Styles", "Staircase Cladding"], "otherServices": ["Floor Maintenance", "Repairs"], "reviewData": [{"author": "The Botha Family", "rating": 5, "comment": "They have a huge range to choose from. The installation was quick and the team was very professional."}] },
      { "id": "lam-003", "name": "TimberLine Midrand", "location": "Midrand", "description": "Affordable laminate flooring supply and installation in Midrand and Kempton Park.", "rating": 4.7, "reviews": 125, "avatarSeed": "timberline-midrand-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 7, "services": ["Laminate Flooring Supply", "Professional Installation", "Budget-friendly options"], "otherServices": ["Vinyl Plank Flooring", "Engineered Wood"], "reviewData": [{"author": "Midrand First-time Homebuyer", "rating": 5, "comment": "Great prices and excellent service. They helped me choose the right floor for my budget."}] },
      { "id": "lam-004", "name": "UrbanPlank Gauteng", "location": "Gauteng", "description": "Modern laminate flooring designs for Gauteng homes.", "rating": 4.8, "reviews": 190, "avatarSeed": "urbanplank-gauteng-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 12, "services": ["Modern Laminate Designs", "Herringbone Patterns", "Wide Plank Flooring"], "otherServices": ["Custom Transitions", "Soundproofing Underlay"], "reviewData": [{"author": "Loft Apartment JHB", "rating": 5, "comment": "If you're looking for something modern and different, this is the company. My herringbone floor is stunning."}] },
      { "id": "lam-005", "name": "SolidStep Floors", "location": "Gauteng", "description": "Quality laminate flooring installations built for long-lasting performance.", "rating": 4.9, "reviews": 110, "avatarSeed": "solidstep-floors-logo", "serviceCategory": "laminate-flooring", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 9, "services": ["High-traffic Laminate", "Commercial Installations", "Quality Guarantee"], "otherServices": ["Water-resistant options", "Sub-floor preparation"], "reviewData": [{"author": "Boksburg Retail Store", "rating": 5, "comment": "We needed something durable for our store, and they delivered. The floor is tough and still looks new after months of heavy foot traffic."}] }
    ],
    "landscaping": [
      { "id": "land-001", "name": "GreenLeaf Sandton Landscapes", "location": "Sandton, Johannesburg", "description": "Professional landscaping services for homes and offices in Sandton, Randburg, and surrounding northern suburbs, including garden design, lawn care, and maintenance.", "rating": 4.9, "reviews": 120, "avatarSeed": "greenleaf-sandton-landscapes-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Garden Design", "Lawn Care", "Regular Maintenance"], "otherServices": ["Irrigation Systems", "Tree Pruning"], "reviewData": [{ "author": "J. Smit", "rating": 5, "comment": "Our garden has never looked better! The team is professional and knowledgeable." }] },
      { "id": "land-002", "name": "Vusi Landscapes PTA", "location": "Pretoria", "description": "Reliable garden design and landscaping solutions throughout Pretoria, Centurion, and nearby areas, offering both residential and commercial outdoor improvements.", "rating": 4.8, "reviews": 95, "avatarSeed": "vuma-landscapes-pta-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 12, "services": ["Garden Design", "Commercial Landscaping", "Residential Maintenance"], "otherServices": ["Water Features", "Paving"], "reviewData": [{ "author": "Mrs. van der Merwe", "rating": 5, "comment": "Vuma transformed our tired garden into a beautiful, low-maintenance space." }] },
      { "id": "land-003", "name": "Khu Garden Midrand", "location": "Midrand", "description": "Affordable landscaping and garden maintenance services in Midrand, serving estates and homes across Kempton Park and nearby suburbs.", "rating": 4.7, "reviews": 110, "avatarSeed": "khula-garden-midrand-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 8, "services": ["Garden Maintenance", "Lawn Mowing", "Planting Services"], "otherServices": ["Weed Control", "Fertilizing"], "reviewData": [{ "author": "T. Khumalo", "rating": 5, "comment": "Reliable and affordable. My garden is always neat and tidy." }] },
      { "id": "land-004", "name": "EdenScape Gauteng", "location": "Gauteng", "description": "Complete outdoor landscaping solutions across Gauteng, including Sandton, Boksburg, and Pretoria, from soft landscaping to full garden makeovers.", "rating": 4.8, "reviews": 150, "avatarSeed": "edenscape-gauteng-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 20, "services": ["Full Garden Makeovers", "Soft Landscaping", "Commercial Maintenance"], "otherServices": ["Irrigation Installation", "Hardscaping"], "reviewData": [{ "author": "Boksburg Business Park", "rating": 5, "comment": "EdenScape manages all our commercial properties' gardens. They are professional and reliable." }] },
      { "id": "land-005", "name": "TerraGrow Projects", "location": "Gauteng", "description": "Custom landscape design and garden improvement services tailored for residential and commercial properties across Gauteng.", "rating": 4.7, "reviews": 80, "avatarSeed": "terragrow-projects-logo", "serviceCategory": "landscaping", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 10, "services": ["Custom Landscape Design", "Garden Improvements", "Project Management"], "otherServices": ["Outdoor Lighting", "Decking"], "reviewData": [{ "author": "L. Naidoo", "rating": 5, "comment": "They had fantastic ideas for my small garden space and executed the project perfectly." }] }
    ],
    "laundry-services": [
        { "id": "laundry-001", "name": "FreshFold Sandton Laundry", "location": "Sandton, Johannesburg", "description": "Convenient laundry and ironing services for households in Sandton and Randburg.", "rating": 4.8, "reviews": 150, "avatarSeed": "freshfold-sandton-logo", "serviceCategory": "laundry-services", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 10, "services": ["Wash & Fold", "Ironing Service", "Collection & Delivery"], "otherServices": ["Duvet & Blanket Cleaning", "Curtain Cleaning"], "reviewData": [{"author": "Sandton Professional", "rating": 5, "comment": "A lifesaver for a busy professional. My laundry is always perfectly done and delivered on time."}] },
        { "id": "laundry-002", "name": "SkoonWas PTA", "location": "Pretoria", "description": "Reliable laundry cleaning services across Pretoria with fast turnaround times.", "rating": 4.7, "reviews": 180, "avatarSeed": "skoonwas-pta-logo", "serviceCategory": "laundry-services", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 12, "services": ["Bulk Laundry", "Student Laundry Deals", "Dry Cleaning"], "otherServices": ["Linen & Towel Service", "Alterations"], "reviewData": [{"author": "Pretoria Student", "rating": 5, "comment": "Great prices for students and they are always fast. My laundry comes back smelling amazing."}] },
        { "id": "laundry-003", "name": "CleanWear Midrand", "location": "Midrand", "description": "Professional laundry services serving Midrand and Kempton Park clients.", "rating": 4.8, "reviews": 130, "avatarSeed": "cleanwear-midrand-logo", "serviceCategory": "laundry-services", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 4, "employees": 8, "services": ["Corporate & Hospitality Laundry", "Wash & Iron", "Stain Removal"], "otherServices": ["Shoe Cleaning", "Leather Cleaning"], "reviewData": [{"author": "Midrand Boutique Hotel", "rating": 5, "comment": "They handle all our hotel linen and the quality is consistently excellent. Very reliable."}] },
        { "id": "laundry-004", "name": "UrbanWash Gauteng", "location": "Gauteng", "description": "Affordable laundry solutions for residential and small business clients across Gauteng.", "rating": 4.7, "reviews": 220, "avatarSeed": "urbanwash-gauteng-logo", "serviceCategory": "laundry-services", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 15, "services": ["Family Laundry Bundles", "Small Business Laundry", "Collection Service"], "otherServices": ["Sports Kit Cleaning", "Curtain Cleaning"], "reviewData": [{"author": "Johannesburg Family", "rating": 5, "comment": "Their family bundle is great value. Saves me so much time every week."}] },
        { "id": "laundry-005", "name": "QuickSpin Laundry", "location": "Gauteng", "description": "Efficient wash-and-fold services tailored to busy households.", "rating": 4.9, "reviews": 160, "avatarSeed": "quickspin-laundry-logo", "serviceCategory": "laundry-services", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 3, "employees": 5, "services": ["Same-day Service", "Wash, Dry & Fold", "Subscription Plans"], "otherServices": ["Bedding", "Towels"], "reviewData": [{"author": "Randburg Mom", "rating": 5, "comment": "The name says it all. Quick, efficient, and the quality is great. I love their subscription service."}] }
    ],
    "locksmiths": [
      { "id": "lock-001", "name": "SecureKey Sandton", "location": "Sandton, Johannesburg", "description": "Fast and reliable locksmith services for homes and businesses in Sandton, Randburg, and nearby areas, including lock repairs and replacements.", "rating": 4.9, "reviews": 280, "avatarSeed": "securekey-sandton-logo", "serviceCategory": "locksmiths", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 10, "services": ["Emergency Lockouts", "Lock Repair & Replacement", "Key Cutting"], "otherServices": ["Security Upgrades", "Safe Opening"], "reviewData": [{"author": "Sandton Resident", "rating": 5, "comment": "They arrived within 20 minutes when I was locked out. Very fast and professional service."}] },
      { "id": "lock-002", "name": "Vala Lock Pros PTA", "location": "Pretoria", "description": "Professional locksmith solutions across Pretoria and Centurion, offering lock installations, emergency assistance, and security upgrades.", "rating": 4.8, "reviews": 210, "avatarSeed": "vala-lock-pros-pta-logo", "serviceCategory": "locksmiths", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 8, "services": ["24/7 Emergency Locksmith", "New Lock Installation", "Security Assessments"], "otherServices": ["Transponder Keys", "Gate Lock Repairs"], "reviewData": [{"author": "Centurion Homeowner", "rating": 5, "comment": "Very knowledgeable. They upgraded all the locks at my new house and provided great security advice."}] },
      { "id": "lock-003", "name": "FastKey Midrand", "location": "Midrand", "description": "Emergency and scheduled locksmith services in Midrand, Kempton Park, and surrounding business and residential areas.", "rating": 4.8, "reviews": 190, "avatarSeed": "fastkey-midrand-logo", "serviceCategory": "locksmiths", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 6, "services": ["Emergency Lockouts", "Vehicle Locksmith", "Residential & Commercial Locks"], "otherServices": ["Key Duplication", "Lock Maintenance"], "reviewData": [{"author": "Midrand Office Park", "rating": 5, "comment": "Fast, reliable, and always available when we need them for office lockouts or key issues."}] },
      { "id": "lock-004", "name": "IronGrip Gauteng", "location": "Gauteng", "description": "Trusted locksmith specialists serving clients across Gauteng, including Boksburg, Sandton, and Pretoria, with quick response times.", "rating": 4.7, "reviews": 350, "avatarSeed": "irongrip-gauteng-logo", "serviceCategory": "locksmiths", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 20, "services": ["Mobile Locksmith Service", "All Lock Types", "Security Solutions"], "otherServices": ["Master Key Systems", "Digital Lock Installation"], "reviewData": [{"author": "Boksburg Resident", "rating": 5, "comment": "Their mobile unit came to my house and sorted out my broken lock in no time. Excellent service."}] },
      { "id": "lock-005", "name": "SafeGuard Locks", "location": "Gauteng", "description": "Secure and affordable locking solutions for residential properties across Gauteng suburbs.", "rating": 4.8, "reviews": 240, "avatarSeed": "safeguard-locks-logo", "serviceCategory": "locksmiths", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 15, "services": ["Residential Locksmith", "Lock Upgrades", "Key Alike Services"], "otherServices": ["Garage Door Locks", "Padlocks"], "reviewData": [{"author": "Roodepoort Family", "rating": 5, "comment": "They re-keyed all our locks after we moved in. Felt much safer, and the service was friendly and affordable."}] }
    ],
    "office-cleaning": [
        { "id": "office-clean-001", "name": "ClearDesk Sandton", "location": "Sandton, Johannesburg", "description": "Professional office cleaning services for corporate spaces in Sandton, Randburg, and major business hubs.", "rating": 4.9, "reviews": 200, "avatarSeed": "cleardesk-sandton-logo", "serviceCategory": "office-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 30, "services": ["Daily Office Cleaning", "Corporate Cleaning Contracts", "Deep Cleaning"], "otherServices": ["Carpet Cleaning", "Window Cleaning"], "reviewData": [{"author": "Sandton Law Firm", "rating": 5, "comment": "Absolutely professional and discreet. Our offices have never been cleaner. Highly recommended."}] },
        { "id": "office-clean-002", "name": "ProOffice Clean PTA", "location": "Pretoria", "description": "Reliable office cleaning tailored for Pretoria-based businesses, ensuring clean and hygienic work environments.", "rating": 4.8, "reviews": 170, "avatarSeed": "prooffice-clean-pta-logo", "serviceCategory": "office-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 25, "services": ["Office Cleaning", "Commercial Sanitation", "Contract Cleaning"], "otherServices": ["Floor Care", "Ablution Deep Cleaning"], "reviewData": [{"author": "Pretoria Tech Hub", "rating": 5, "comment": "A very reliable team. They are flexible with our hours and always do a thorough job."}] },
        { "id": "office-clean-003", "name": "SkoonWorkplace Midrand", "location": "Midrand", "description": "Consistent and hygienic office cleaning solutions for offices in Midrand, Kempton Park, and nearby commercial areas.", "rating": 4.8, "reviews": 150, "avatarSeed": "skoonworkplace-midrand-logo", "serviceCategory": "office-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 20, "services": ["Scheduled Office Cleaning", "Hygiene Services", "Once-off Deep Cleans"], "otherServices": ["Post-event Cleaning", "Common Area Maintenance"], "reviewData": [{"author": "Midrand Logistics Co.", "rating": 5, "comment": "They keep our large office and warehouse areas consistently clean. Very happy with their service."}] },
        { "id": "office-clean-004", "name": "Khanya Office Care", "location": "Gauteng", "description": "Commercial cleaning solutions across Gauteng, serving offices in Sandton, Boksburg, and Pretoria.", "rating": 4.7, "reviews": 250, "avatarSeed": "khanya-office-care-logo", "serviceCategory": "office-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 40, "services": ["Commercial Cleaning", "Office Park Maintenance", "Retail Cleaning"], "otherServices": ["High-access Window Cleaning", "Pest Control"], "reviewData": [{"author": "Gauteng Business Park", "rating": 5, "comment": "Khanya manages the cleaning for our entire business park. They are professional, well-equipped, and very responsive."}] },
        { "id": "office-clean-005", "name": "PrimeSpace Cleaning", "location": "Gauteng", "description": "Efficient cleaning services for offices and workspaces, supporting businesses across Gauteng.", "rating": 4.9, "reviews": 180, "avatarSeed": "primespace-cleaning-logo", "serviceCategory": "office-cleaning", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 22, "services": ["Workspace Cleaning", "Flexible Contracts", "Eco-friendly Cleaning"], "otherServices": ["IT Equipment Sanitization", "Boardroom Cleaning"], "reviewData": [{"author": "Johannesburg Startup", "rating": 5, "comment": "Perfect for a modern workspace. They use eco-friendly products and are very thorough."}] }
    ],
    "painters": [
      { "id": "paint-001", "name": "PerfectCoat Sandton", "location": "Sandton, Johannesburg", "description": "Professional interior and exterior painting services for homes and offices in Sandton and Randburg.", "rating": 4.9, "reviews": 220, "avatarSeed": "perfectcoat-sandton-logo", "serviceCategory": "painters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Interior Painting", "Exterior Painting", "Commercial Painting"], "otherServices": ["Roof Painting", "Waterproofing"], "reviewData": [{"author": "Sandton Homeowner", "rating": 5, "comment": "Impeccable work. The lines are clean, the finish is smooth, and they left the place spotless."}] },
      { "id": "paint-002", "name": "VividBrush PTA", "location": "Pretoria", "description": "High-quality residential and commercial painting services across Pretoria and surrounding suburbs.", "rating": 4.8, "reviews": 180, "avatarSeed": "vividbrush-pta-logo", "serviceCategory": "painters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 12, "services": ["Residential Painting", "Commercial Projects", "Colour Consultation"], "otherServices": ["Feature Walls", "Skimming"], "reviewData": [{"author": "Pretoria Guest House", "rating": 5, "comment": "They repainted our entire guesthouse, inside and out. The results are fantastic and our guests love it."}] },
      { "id": "paint-003", "name": "Khula PaintWorks Midrand", "location": "Midrand", "description": "Affordable painting services delivering clean, durable finishes in Midrand and Kempton Park.", "rating": 4.7, "reviews": 250, "avatarSeed": "khula-paintworks-midrand-logo", "serviceCategory": "painters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 20, "services": ["Interior & Exterior Painting", "Affordable Quotes", "Quick Turnaround"], "otherServices": ["Varnishing", "Minor Damp Proofing"], "reviewData": [{"author": "Midrand Family", "rating": 5, "comment": "Great value and great work. They painted our whole house in a week."}] },
      { "id": "paint-004", "name": "Elite Finish Gauteng", "location": "Gauteng", "description": "Skilled painters serving Gauteng clients, including Boksburg, Sandton, and Pretoria, with attention to detail.", "rating": 4.9, "reviews": 300, "avatarSeed": "elite-finish-gauteng-logo", "serviceCategory": "painters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 25, "services": ["High-end Residential Painting", "Detailed Prep Work", "Protective Coatings"], "otherServices": ["Specialist Finishes", "Spray Painting"], "reviewData": [{"author": "Architect, Boksburg", "rating": 5, "comment": "When I need a painter who can deliver a flawless finish for a high-end project, I call Elite Finish. Their prep work is meticulous."}] },
      { "id": "paint-005", "name": "SmoothWall Services", "location": "Gauteng", "description": "Reliable painting solutions for homes and offices across Gauteng.", "rating": 4.8, "reviews": 210, "avatarSeed": "smoothwall-services-logo", "serviceCategory": "painters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 18, "services": ["Interior Painting", "Exterior Painting", "Office Repaints"], "otherServices": ["Drywall Repair", "Skimming"], "reviewData": [{"author": "Roodepoort Offices", "rating": 5, "comment": "They did a great job repainting our office over the weekend with minimal disruption. Very efficient."}] }
    ],
    "paving": [
      { "id": "pave-001", "name": "StoneCraft Sandton Paving", "location": "Sandton, Johannesburg", "description": "Expert paving installations for driveways, patios, and walkways in Sandton and Randburg.", "rating": 4.8, "reviews": 160, "avatarSeed": "stonecraft-sandton-paving-logo", "serviceCategory": "paving", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 18, "services": ["Driveway Paving", "Patio Paving", "Walkway Installation"], "otherServices": ["Cobblestone", "Paving Repairs"], "reviewData": [{"author": "Bryanston Homeowner", "rating": 5, "comment": "Our new driveway looks incredible. The workmanship is excellent and the team was very professional."}] },
      { "id": "pave-002", "name": "Vuma Pave PTA", "location": "Pretoria", "description": "Durable and affordable paving solutions across Pretoria, including residential and commercial paving projects.", "rating": 4.7, "reviews": 200, "avatarSeed": "vuma-pave-pta-logo", "serviceCategory": "paving", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 22, "services": ["Residential Paving", "Commercial Paving", "Paving Repairs"], "otherServices": ["Kerbing", "Tar Surfacing"], "reviewData": [{"author": "Pretoria Small Business", "rating": 5, "comment": "They paved our entire parking area. Good price, and the job was completed ahead of schedule."}] },
      { "id": "pave-003", "name": "UrbanBrick Midrand", "location": "Midrand", "description": "Modern paving designs for residential properties in Midrand and Kempton Park.", "rating": 4.8, "reviews": 140, "avatarSeed": "urbanbrick-midrand-logo", "serviceCategory": "paving", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 10, "services": ["Modern Paving", "Interlocking Pavers", "Patio & Pool Surrounds"], "otherServices": ["Permeable Paving", "Cladding"], "reviewData": [{"author": "Midrand Estate Resident", "rating": 5, "comment": "They have beautiful, modern brick options. Our new patio is the highlight of our garden."}] },
      { "id": "pave-004", "name": "SolidWay Gauteng", "location": "Gauteng", "description": "Professional paving contractors serving Gauteng clients, including Boksburg and major metro areas.", "rating": 4.7, "reviews": 280, "avatarSeed": "solidway-gauteng-logo", "serviceCategory": "paving", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 30, "services": ["Industrial Paving", "Heavy-duty Driveways", "Large-scale Paving Projects"], "otherServices": ["Asphalt", "Road Markings"], "reviewData": [{"author": "Boksburg Industrial Park", "rating": 5, "comment": "SolidWay handles all our heavy-duty paving needs. They are professional and deliver quality that lasts."}] },
      { "id": "pave-005", "name": "Khula Pave Projects", "location": "Gauteng", "description": "Custom paving solutions built to last for homes and businesses across Gauteng.", "rating": 4.9, "reviews": 170, "avatarSeed": "khula-pave-projects-logo", "serviceCategory": "paving", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 14, "services": ["Custom Paving Design", "Residential Driveways", "Patio Paving"], "otherServices": ["Retaining Walls", "Garden Edging"], "reviewData": [{"author": "Roodepoort Homeowner", "rating": 5, "comment": "They did a beautiful custom paving design for our entertainment area. We get so many compliments!"}] }
    ],
    "palisade-fencing": [
        { "id": "palisade-001", "name": "IronShield Sandton Fencing", "location": "Sandton, Johannesburg", "description": "Durable palisade fencing installations for homes and businesses in Sandton and Randburg.", "rating": 4.8, "reviews": 130, "avatarSeed": "ironshield-sandton-fencing-logo", "serviceCategory": "palisade-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Palisade Fencing Installation", "Security Gates", "Fence Repairs"], "otherServices": ["Spike Installation", "Rust Treatment"], "reviewData": [{"author": "A. Naicker", "rating": 5, "comment": "Very strong and neat installation. The team was efficient and cleaned up afterwards."}] },
        { "id": "palisade-002", "name": "SecureLine PTA", "location": "Pretoria", "description": "Professional palisade fencing solutions for residential properties across Pretoria.", "rating": 4.7, "reviews": 155, "avatarSeed": "secureline-pta-logo", "serviceCategory": "palisade-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 12, "services": ["Residential Palisade Fencing", "Gate Manufacturing", "Fence Painting"], "otherServices": ["Automation", "Repairs"], "reviewData": [{"author": "P. van der Merwe", "rating": 5, "comment": "Good quality fencing and the installation was quick. I feel much safer now."}] },
        { "id": "palisade-003", "name": "Next Gen Fence Midrand", "location": "Midrand", "description": "Affordable and secure fencing installations in Midrand and Kempton Park.", "rating": 4.6, "reviews": 110, "avatarSeed": "next-gen-fence-midrand-logo", "serviceCategory": "palisade-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 9, "services": ["Palisade Fencing", "Sliding Gates", "General Welding"], "otherServices": ["Repairs", "Maintenance"], "reviewData": [{"author": "Midrand Resident", "rating": 4, "comment": "Good price for the quality. The installation took a bit longer than expected but the result is solid."}] },
        { "id": "palisade-004", "name": "SteelGuard Gauteng", "location": "Gauteng", "description": "Strong and reliable palisade fencing systems serving Gauteng clients.", "rating": 4.8, "reviews": 210, "avatarSeed": "steelguard-gauteng-logo", "serviceCategory": "palisade-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 25, "services": ["Industrial Palisade Fencing", "High-Security Fencing", "Custom Designs"], "otherServices": ["Barbed Wire", "Electric Fence Brackets"], "reviewData": [{"author": "Factory Owner", "rating": 5, "comment": "They installed a heavy-duty fence around our entire property. Very professional and the quality is top-notch."}] },
        { "id": "palisade-005", "name": "ProBarrier Fencing", "location": "Gauteng", "description": "Custom palisade fencing solutions designed for long-term security.", "rating": 4.9, "reviews": 140, "avatarSeed": "probarrier-fencing-logo", "serviceCategory": "palisade-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 11, "services": ["Bespoke Palisade Fencing", "Aesthetic Security", "Galvanized & Coated Options"], "otherServices": ["Integrated Gates", "Repairs"], "reviewData": [{"author": "Complex Manager", "rating": 5, "comment": "They designed a custom fence that matches the aesthetic of our complex perfectly, without compromising on security."}] }
    ],
    "pest-control": [
        { "id": "pest-001", "name": "SafeNest Sandton Pest Control", "location": "Sandton, Johannesburg", "description": "Effective pest control solutions for homes and offices in Sandton and Randburg.", "rating": 4.9, "reviews": 180, "avatarSeed": "safenest-sandton-logo", "serviceCategory": "pest-control", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 10, "services": ["Rodent Control", "Insect Eradication", "Termite Treatment"], "otherServices": ["Preventative Services", "Fumigation"], "reviewData": [{"author": "Sandton Cafe", "rating": 5, "comment": "Fast, discreet, and effective. They solved our rodent problem quickly."}] },
        { "id": "pest-002", "name": "EcoBug PTA", "location": "Pretoria", "description": "Safe and environmentally responsible pest control services across Pretoria.", "rating": 4.8, "reviews": 160, "avatarSeed": "ecobug-pta-logo", "serviceCategory": "pest-control", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 8, "services": ["Eco-friendly Pest Control", "Integrated Pest Management", "Ant & Cockroach Control"], "otherServices": ["Bird Proofing", "Inspections"], "reviewData": [{"author": "Eco-conscious Homeowner", "rating": 5, "comment": "I was looking for a pet-safe option and they were fantastic. Explained everything and used eco-friendly products."}] },
        { "id": "pest-003", "name": "A TO Z PestGuard Midrand", "location": "Midrand", "description": "Reliable pest management services in Midrand and Kempton Park.", "rating": 4.7, "reviews": 140, "avatarSeed": "atoz-pestguard-midrand-logo", "serviceCategory": "pest-control", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 11, "employees": 14, "services": ["Residential Pest Control", "Commercial Contracts", "All Pest Types"], "otherServices": ["Termite Inspections", "Rodent Proofing"], "reviewData": [{"author": "Midrand Warehouse", "rating": 5, "comment": "They handle our monthly pest control contract and are always thorough and reliable."}] },
        { "id": "pest-004", "name": "RapidShield Gauteng", "location": "Gauteng", "description": "Fast-acting pest control solutions serving Gauteng clients, including Boksburg.", "rating": 4.8, "reviews": 220, "avatarSeed": "rapidshield-gauteng-logo", "serviceCategory": "pest-control", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 20, "services": ["Emergency Pest Control", "Fumigation Services", "Wasp & Bee Removal"], "otherServices": ["Spider Control", "Fishmoth Treatment"], "reviewData": [{"author": "Boksburg Family", "rating": 5, "comment": "Had a huge cockroach problem and they sorted it out in one visit. Very effective."}] },
        { "id": "pest-005", "name": "CleanZone Pest Control", "location": "Gauteng", "description": "Affordable pest prevention and treatment services for residential properties.", "rating": 4.7, "reviews": 190, "avatarSeed": "cleanzone-pest-control-logo", "serviceCategory": "pest-control", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 10, "services": ["Preventative Treatments", "Ant Control", "Rodent Bait Stations"], "otherServices": ["Inspections", "Follow-up visits"], "reviewData": [{"author": "New Homeowner", "rating": 5, "comment": "They did a preventative treatment when we moved in. Very thorough and gave us great advice. Haven't seen a single pest."}] }
    ],
    "plastering": [
        { "id": "plaster-001", "name": "SmoothFinish Sandton", "location": "Sandton, Johannesburg", "description": "Professional plastering services for walls and ceilings in Sandton and Randburg.", "rating": 4.9, "reviews": 110, "avatarSeed": "smoothfinish-sandton-logo", "serviceCategory": "plastering", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 10, "services": ["Interior Plastering", "Skimming", "Ceiling Plastering"], "otherServices": ["Drywall Jointing", "Crack Repairs"], "reviewData": [{"author": "Renovator in Sandton", "rating": 5, "comment": "The finish is like glass. Absolutely perfect plastering work."}] },
        { "id": "plaster-002", "name": "ProPlaster PTA", "location": "Pretoria", "description": "Quality plastering solutions for residential projects across Pretoria.", "rating": 4.8, "reviews": 140, "avatarSeed": "proplaster-pta-logo", "serviceCategory": "plastering", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 12, "services": ["Exterior & Interior Plastering", "Renovations", "New Builds"], "otherServices": ["Decorative Plaster", "Damp Proofing"], "reviewData": [{"author": "Pretoria Home Builder", "rating": 5, "comment": "We use ProPlaster for all our new builds. They are reliable and the quality is consistent."}] },
        { "id": "plaster-003", "name": "B.I.G Wall Midrand", "location": "Midrand", "description": "Affordable plastering and surface finishing services in Midrand and Kempton Park.", "rating": 4.7, "reviews": 120, "avatarSeed": "big-wall-midrand-logo", "serviceCategory": "plastering", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 9, "services": ["Wall Plastering", "Ceiling Repairs", "Skimming"], "otherServices": ["Painting Preparation", "Cornice Installation"], "reviewData": [{"author": "Kempton Park Homeowner", "rating": 5, "comment": "Good quality work at a fair price. Very happy with the results."}] },
        { "id": "plaster-004", "name": "Elite Surface Gauteng", "location": "Gauteng", "description": "Skilled plastering contractors serving Gauteng homes and offices.", "rating": 4.8, "reviews": 190, "avatarSeed": "elite-surface-gauteng-logo", "serviceCategory": "plastering", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 18, "services": ["High-end Plaster Finishes", "Commercial Plastering", "Residential Projects"], "otherServices": ["Rhinolite Application", "Wall Screeding"], "reviewData": [{"author": "Interior Designer", "rating": 5, "comment": "For a perfect, high-end finish, I only trust Elite Surface. Their attention to detail is unmatched."}] },
        { "id": "plaster-005", "name": "EvenWall Services", "location": "Gauteng", "description": "Reliable plastering solutions ensuring smooth and durable finishes.", "rating": 4.7, "reviews": 160, "avatarSeed": "evenwall-services-logo", "serviceCategory": "plastering", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 10, "services": ["Plastering Repairs", "Full Wall Plastering", "Ceiling Skimming"], "otherServices": ["Crack Filling", "Surface Preparation"], "reviewData": [{"author": "Property Manager", "rating": 5, "comment": "They handle all the plaster repairs for our rental units. Always a professional and neat job."}] }
    ],
    "roofer": [
        { "id": "roof-001", "name": "Bravo Projects", "location": "Randburg", "description": "Reliable and experienced roofing contractors for {service} repairs, waterproofing, and new installations. No job is too big or small.", "rating": 4.9, "reviews": 185, "isProVerified": true, "avatarSeed": "roofer-image", "serviceCategory": "roofer", "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 20, "services": ["Roof Leak Repairs", "Waterproofing", "New Roof Installations"], "otherServices": ["Gutter Cleaning", "Roof Painting"], "reviewData": [{"author": "T. Molefe", "rating": 5, "comment": "They found and fixed a persistent leak that two other companies couldn't. Very knowledgeable and professional."}] }
    ],
    "precast-fencing": [
        { "id": "precast-001", "name": "SolidCast Sandton Fencing", "location": "Sandton, Johannesburg", "description": "Strong precast concrete fencing installations in Sandton and Randburg.", "rating": 4.8, "reviews": 120, "avatarSeed": "solidcast-sandton-fencing-logo", "serviceCategory": "precast-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 11, "employees": 14, "services": ["Precast Wall Installation", "Wall Extensions", "Repairs"], "otherServices": ["Gates", "Painting"], "reviewData": [{"author": "J. Pienaar", "rating": 5, "comment": "The new wall went up so quickly and it looks great. Very sturdy."}] },
        { "id": "precast-002", "name": "PreForm PTA", "location": "Pretoria", "description": "Professional precast fencing solutions for residential properties across Pretoria.", "rating": 4.7, "reviews": 140, "avatarSeed": "preform-pta-logo", "serviceCategory": "precast-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 11, "services": ["Residential Precast Fencing", "Various Styles", "Repairs"], "otherServices": ["Gates", "Raising Walls"], "reviewData": [{"author": "Pretoria Resident", "rating": 5, "comment": "Excellent service and a good price. They were very neat and tidy during the installation."}] },
        { "id": "precast-003", "name": "STANLEY Concrete Midrand", "location": "Midrand", "description": "Durable precast fencing services in Midrand and Kempton Park.", "rating": 4.7, "reviews": 100, "avatarSeed": "stanley-concrete-midrand-logo", "serviceCategory": "precast-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 20, "employees": 25, "services": ["Precast Fencing", "Stop-Nonsense Walls", "Industrial Walling"], "otherServices": ["Repairs", "Extensions"], "reviewData": [{"author": "Midrand Smallholding", "rating": 5, "comment": "You can't beat their quality. A very strong and secure wall."}] },
        { "id": "precast-004", "name": "BuildSafe Gauteng", "location": "Gauteng", "description": "Reliable concrete fencing systems serving Gauteng areas.", "rating": 4.8, "reviews": 190, "avatarSeed": "buildsafe-gauteng-logo", "serviceCategory": "precast-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 14, "employees": 22, "services": ["Concrete Fencing", "Security Walling", "Repairs"], "otherServices": ["Gates", "Painting"], "reviewData": [{"author": "Gauteng Homeowner", "rating": 5, "comment": "They were quick to respond and the installation was done professionally. I feel much safer."}] },
        { "id": "precast-005", "name": "Urban Systems", "location": "Gauteng", "description": "Long-lasting precast fencing designed for security and durability.", "rating": 4.9, "reviews": 115, "avatarSeed": "urban-systems-logo", "serviceCategory": "precast-fencing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 16, "services": ["Precast Walling", "Fence Extensions", "Custom Walling"], "otherServices": ["Security Features", "Repairs"], "reviewData": [{"author": "Complex Manager", "rating": 5, "comment": "They handled the walling for our entire complex. Very professional and the quality is excellent."}] }
    ],
    "prepaid-electricity-meters": [
        { "id": "prepaid-001", "name": "PowerPay Sandton", "location": "Sandton, Johannesburg", "description": "Professional prepaid electricity meter installations in Sandton and Randburg.", "rating": 4.8, "reviews": 90, "avatarSeed": "powerpay-sandton-logo", "serviceCategory": "prepaid-electricity-meters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 8, "services": ["Prepaid Meter Installation", "Sub-metering", "Support"], "otherServices": ["Vending", "Troubleshooting"], "reviewData": [{"author": "Landlord in Sandton", "rating": 5, "comment": "Made managing my rental units so much easier. The installation was quick and professional."}] },
        { "id": "prepaid-002", "name": "SmartMeter PTA", "location": "Pretoria", "description": "Reliable prepaid meter installation and maintenance services across Pretoria.", "rating": 4.7, "reviews": 110, "avatarSeed": "smartmeter-pta-logo", "serviceCategory": "prepaid-electricity-meters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 10, "services": ["Prepaid Meter Installation", "Maintenance", "Troubleshooting"], "otherServices": ["Vending Solutions", "Support"], "reviewData": [{"author": "Pretoria Homeowner", "rating": 5, "comment": "Great service. They explained everything clearly and the installation was neat."}] },
        { "id": "prepaid-003", "name": "MID Energy Midrand", "location": "Midrand", "description": "Affordable prepaid electricity solutions in Midrand and Kempton Park.", "rating": 4.6, "reviews": 80, "avatarSeed": "mid-energy-midrand-logo", "serviceCategory": "prepaid-electricity-meters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 5, "employees": 6, "services": ["Prepaid Meter Installation", "Sub-metering", "Vending"], "otherServices": ["Support", "Repairs"], "reviewData": [{"author": "Property Developer", "rating": 5, "comment": "Good pricing for bulk installations. They are our go-to for new developments."}] },
        { "id": "prepaid-004", "name": "EasyWatt Gauteng", "location": "Gauteng", "description": "Prepaid electricity meter services for residential properties across Gauteng.", "rating": 4.8, "reviews": 150, "avatarSeed": "easywatt-gauteng-logo", "serviceCategory": "prepaid-electricity-meters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 12, "services": ["Prepaid Meter Installation", "Support", "Vending"], "otherServices": ["Troubleshooting", "Maintenance"], "reviewData": [{"author": "Gauteng Landlord", "rating": 5, "comment": "They make it so easy to manage electricity for my tenants. Highly recommend."}] },
        { "id": "prepaid-005", "name": "GridPoint Installers", "location": "Gauteng", "description": "Efficient and compliant prepaid meter installations.", "rating": 4.9, "reviews": 95, "avatarSeed": "gridpoint-installers-logo", "serviceCategory": "prepaid-electricity-meters", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 7, "services": ["Prepaid Meter Installation", "Compliance Checks", "Support"], "otherServices": ["Vending", "Repairs"], "reviewData": [{"author": "Homeowner", "rating": 5, "comment": "Very professional and efficient service. The installer was friendly and explained how everything works."}] }
    ],
    "roofing": [
        { "id": "roofing-001", "name": "StrongPeak Sandton Roofing", "location": "Sandton, Johannesburg", "description": "Professional roofing repairs and installations for homes in Sandton and Randburg.", "rating": 4.9, "reviews": 200, "avatarSeed": "strongpeak-sandton-roofing-logo", "serviceCategory": "roofing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 18, "services": ["Roof Repairs", "New Roof Installations", "Waterproofing"], "otherServices": ["Guttering", "Roof Painting"], "reviewData": [{"author": "Sandton Resident", "rating": 5, "comment": "They fixed our roof leak just before the big rains. Very professional and a high standard of work."}] },
        { "id": "roofing-002", "name": "R.R.R Roof Works PTA", "location": "Pretoria", "description": "Reliable roofing solutions including leak repairs across Pretoria.", "rating": 4.8, "reviews": 180, "avatarSeed": "rrr-roof-works-pta-logo", "serviceCategory": "roofing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 20, "services": ["Roof Leak Repairs", "Waterproofing", "Tile Replacement"], "otherServices": ["Gutter Cleaning", "Roof Maintenance"], "reviewData": [{"author": "Pretoria Homeowner", "rating": 5, "comment": "Fast and effective. They found the leak and repaired it properly. No issues since."}] },
        { "id": "roofing-003", "name": "IronTop Midrand", "location": "Midrand", "description": "Affordable roofing services in Midrand and Kempton Park.", "rating": 4.7, "reviews": 150, "avatarSeed": "irontop-midrand-logo", "serviceCategory": "roofing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 12, "services": ["Roof Repairs", "Waterproofing", "Roof Painting"], "otherServices": ["Gutter Repairs", "Maintenance"], "reviewData": [{"author": "Midrand Homeowner", "rating": 5, "comment": "Good price and they did a great job painting our roof. It looks brand new."}] },
        { "id": "roofing-004", "name": "SecureSpan Gauteng", "location": "Gauteng", "description": "Roofing contractors serving Boksburg and surrounding areas.", "rating": 4.8, "reviews": 250, "avatarSeed": "securespan-gauteng-logo", "serviceCategory": "roofing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 20, "employees": 30, "services": ["New Roofs", "Re-roofing", "Waterproofing"], "otherServices": ["Industrial Roofing", "Guttering"], "reviewData": [{"author": "Boksburg Business", "rating": 5, "comment": "They re-roofed our entire warehouse. A big job that was handled very professionally."}] },
        { "id": "roofing-005", "name": "ProShield Roofs", "location": "Gauteng", "description": "Durable roofing solutions designed to protect homes long-term.", "rating": 4.9, "reviews": 190, "avatarSeed": "proshield-roofs-logo", "serviceCategory": "roofing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 15, "services": ["Roofing Systems", "Waterproofing Membranes", "Maintenance Plans"], "otherServices": ["Insulation", "Ventilation"], "reviewData": [{"author": "Gauteng Homeowner", "rating": 5, "comment": "They offer a complete roofing system, not just a quick fix. Very thorough and professional."}] }
    ],
    "shadeports": [
      { "id": "shade-001", "name": "SunGuard Shadeports", "location": "Gauteng", "description": "Custom shadeport installations for homes, offices, and parking areas across Gauteng, offering durable and weather-resistant shade solutions.", "rating": 4.8, "reviews": 150, "avatarSeed": "sunguard-shadeports-logo", "serviceCategory": "shadeports", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 12, "services": ["Carports", "Patio Shades", "Custom Installations"], "otherServices": ["Shade Net Replacement", "Repairs"], "reviewData": [{"author": "A. Singh", "rating": 5, "comment": "Excellent quality and installation. The new shadeport looks great and is very sturdy."}] },
      { "id": "shade-002", "name": "Mzansi Shade Structures", "location": "Gauteng", "description": "Affordable steel and fabric shadeports designed for long-lasting protection for vehicles and outdoor spaces.", "rating": 4.7, "reviews": 130, "avatarSeed": "mzansi-shade-structures-logo", "serviceCategory": "shadeports", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 10, "services": ["Steel Carports", "Fabric Shadeports", "Repairs"], "otherServices": ["Custom Sizes", "Waterproof Options"], "reviewData": [{"author": "P. Naidoo", "rating": 5, "comment": "Great value for money. They installed a double carport for us and we are very happy with the result."}] },
      { "id": "shade-003", "name": "UrbanCover Shadeports", "location": "Gauteng", "description": "Modern shadeport designs for residential estates, schools, and commercial properties.", "rating": 4.9, "reviews": 110, "avatarSeed": "urbancover-shadeports-logo", "serviceCategory": "shadeports", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 6, "employees": 8, "services": ["Modern Designs", "Large-scale Projects", "Cantilever Shadeports"], "otherServices": ["Maintenance Contracts", "Netting Repairs"], "reviewData": [{"author": "School Principal", "rating": 5, "comment": "They installed shadeports over our entire playground. The design is modern and safe for the children."}] },
      { "id": "shade-004", "name": "BOSSA Shade Solutions", "location": "Gauteng", "description": "Reliable shadeport installation and repairs with a focus on quality workmanship and customer satisfaction.", "rating": 4.8, "reviews": 160, "avatarSeed": "bossa-shade-solutions-logo", "serviceCategory": "shadeports", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 18, "services": ["Shadeport Installation", "Repairs", "Net Replacement"], "otherServices": ["Tensioning", "Structure Painting"], "reviewData": [{"author": "G. Botha", "rating": 5, "comment": "Very professional service from start to finish. Our old shadeport net was replaced and it looks brand new."}] },
      { "id": "shade-005", "name": "PrimeShade Gauteng", "location": "Gauteng", "description": "Professional shadeport construction including carports, walkways, and outdoor covers.", "rating": 4.7, "reviews": 140, "avatarSeed": "primeshade-gauteng-logo", "serviceCategory": "shadeports", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 11, "services": ["Carports", "Walkway Covers", "Custom Shade Solutions"], "otherServices": ["Pool Covers", "Patio Shades"], "reviewData": [{"author": "J. van Zyl", "rating": 5, "comment": "They built a custom walkway cover for our office park. Excellent workmanship."}] }
    ],
    "shower-doors": [
      { "id": "shower-001", "name": "CrystalFlow Shower Doors", "location": "Gauteng", "description": "Custom glass shower doors and enclosures designed for modern bathrooms across Gauteng.", "rating": 4.9, "reviews": 180, "avatarSeed": "crystalflow-shower-doors-logo", "serviceCategory": "shower-doors", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 10, "services": ["Frameless Shower Doors", "Custom Enclosures", "Sliding Doors"], "otherServices": ["Glass Balustrades", "Mirrors"], "reviewData": [{"author": "M. Williams", "rating": 5, "comment": "The frameless shower door completely transformed my bathroom. Flawless installation."}] },
      { "id": "shower-002", "name": "ClearView Showers", "location": "Gauteng", "description": "Frameless and semi-frameless shower door installations with high-quality safety glass.", "rating": 4.8, "reviews": 160, "avatarSeed": "clearview-showers-logo", "serviceCategory": "shower-doors", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 14, "services": ["Frameless Installations", "Semi-frameless Doors", "Safety Glass"], "otherServices": ["Repairs", "Seal Replacement"], "reviewData": [{"author": "D. Jones", "rating": 5, "comment": "Very professional and the quality is excellent. They took precise measurements for a perfect fit."}] },
      { "id": "shower-003", "name": "AquaStyle Shower Solutions", "location": "Gauteng", "description": "Stylish shower door designs tailored for bathroom renovations and new builds.", "rating": 4.7, "reviews": 130, "avatarSeed": "aquastyle-shower-solutions-logo", "serviceCategory": "shower-doors", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 8, "services": ["Modern Shower Doors", "Pivot Doors", "Corner Units"], "otherServices": ["Custom Etching", "Hardware Selection"], "reviewData": [{"author": "K. Adams", "rating": 5, "comment": "They had a great selection of modern styles. Our new shower door is the centerpiece of the bathroom."}] },
      { "id": "shower-004", "name": "Mzansi Glass Showers", "location": "Gauteng", "description": "Affordable shower door supply and installation for residential properties.", "rating": 4.6, "reviews": 190, "avatarSeed": "mzansi-glass-showers-logo", "serviceCategory": "shower-doors", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 11, "services": ["Affordable Shower Doors", "Standard Sizes", "Quick Installation"], "otherServices": ["Repairs", "Sealant"], "reviewData": [{"author": "T. Molefe", "rating": 4, "comment": "Good value for a standard installation. The job was done quickly and neatly."}] },
      { "id": "shower-005", "name": "PureLine Shower Doors", "location": "Gauteng", "description": "Precision-fitted shower enclosures delivering sleek finishes and long-term durability.", "rating": 4.9, "reviews": 140, "avatarSeed": "pureline-shower-doors-logo", "serviceCategory": "shower-doors", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 9, "services": ["Precision Installation", "Frameless Systems", "Minimalist Design"], "otherServices": ["Waterproofing coordination", "Maintenance"], "reviewData": [{"author": "S. Patel", "rating": 5, "comment": "The attention to detail was impressive. The final result is a clean, minimalist look that we wanted."}] }
    ],
    "solar-geysers": [
      { "id": "solar-geyser-001", "name": "SunHeat Solar Geysers", "location": "Gauteng", "description": "Energy-efficient solar geyser installations helping households reduce electricity costs.", "rating": 4.8, "reviews": 210, "avatarSeed": "sunheat-solar-geysers-logo", "serviceCategory": "solar-geysers", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 15, "services": ["Solar Geyser Installation", "System Servicing", "Evacuated Tube Systems"], "otherServices": ["Heat Pumps", "Maintenance"], "reviewData": [{"author": "C. Botha", "rating": 5, "comment": "Excellent investment. The installation was professional and our electricity bill has dropped significantly."}] },
      { "id": "solar-geyser-002", "name": "EcoHot Water Systems", "location": "Gauteng", "description": "Reliable solar hot water solutions for homes, complexes, and small businesses.", "rating": 4.7, "reviews": 180, "avatarSeed": "ecohot-water-systems-logo", "serviceCategory": "solar-geysers", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 11, "services": ["Solar Water Heating", "Commercial Systems", "Residential Installations"], "otherServices": ["Repairs", "System Upgrades"], "reviewData": [{"author": "Complex Body Corporate", "rating": 5, "comment": "They installed solar geysers for our entire complex. The project was well-managed and the savings are real."}] },
      { "id": "solar-geyser-003", "name": "Mzansi Solar Geysers", "location": "Gauteng", "description": "Affordable solar geyser supply, installation, and maintenance across Gauteng.", "rating": 4.6, "reviews": 220, "avatarSeed": "mzansi-solar-geysers-logo", "serviceCategory": "solar-geysers", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 10, "services": ["Affordable Installations", "Maintenance", "Repairs"], "otherServices": ["Tube Replacement", "System Checks"], "reviewData": [{"author": "T. Ndlovu", "rating": 4, "comment": "Good price and the system works well. Took a bit longer to install but happy with the outcome."}] },
      { "id": "solar-geyser-004", "name": "GreenFlow Solar Heating", "location": "Gauteng", "description": "Professional solar geyser solutions focused on sustainability and performance.", "rating": 4.9, "reviews": 160, "avatarSeed": "greenflow-solar-heating-logo", "serviceCategory": "solar-geysers", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 14, "services": ["High-Performance Systems", "Eco-friendly Solutions", "Energy Audits"], "otherServices": ["System Optimization", "Repairs"], "reviewData": [{"author": "Eco-Lodge Owner", "rating": 5, "comment": "Their expertise in sustainable heating is impressive. Our new system is highly efficient and eco-friendly."}] },
      { "id": "solar-geyser-005", "name": "AquaSun Installations", "location": "Gauteng", "description": "High-quality solar water heating systems with expert installation teams.", "rating": 4.8, "reviews": 190, "avatarSeed": "aquasun-installations-logo", "serviceCategory": "solar-geysers", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 11, "employees": 16, "services": ["Solar Geyser Installation", "Quality Components", "Expert Advice"], "otherServices": ["System Servicing", "Leak Repairs"], "reviewData": [{"author": "R. van Jaarsveld", "rating": 5, "comment": "The quality of the components and the installation itself was top-notch. You can tell they are experts."}] }
    ],
    "solar-systems": [
        { "id": "solar-sys-001", "name": "SolarWise Gauteng", "location": "Gauteng", "description": "Complete solar power systems including panels, inverters, and battery storage solutions.", "rating": 4.9, "reviews": 250, "avatarSeed": "solarwise-gauteng-logo", "serviceCategory": "solar-systems", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 20, "services": ["Full Solar Systems", "Battery Backups", "Grid-Tied & Hybrid"], "otherServices": ["Energy Audits", "COC for Solar"], "reviewData": [{"author": "Johannesburg Homeowner", "rating": 5, "comment": "A seamless process from consultation to installation. Our loadshedding worries are over."}] },
        { "id": "solar-sys-002", "name": "Solar Tech", "location": "Gauteng", "description": "Residential and commercial solar installations designed for South African power needs.", "rating": 4.8, "reviews": 220, "avatarSeed": "solar-tech-logo", "serviceCategory": "solar-systems", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 25, "services": ["Residential Solar", "Commercial Installations", "System Maintenance"], "otherServices": ["Panel Cleaning", "Inverter Repairs"], "reviewData": [{"author": "Pretoria Business Owner", "rating": 5, "comment": "They installed a large system for our offices. The savings on our electricity bill are significant."}] },
        { "id": "solar-sys-003", "name": "BrightGrid Energy", "location": "Gauteng", "description": "Custom solar energy systems helping clients achieve energy independence.", "rating": 4.8, "reviews": 180, "avatarSeed": "brightgrid-energy-logo", "serviceCategory": "solar-systems", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 15, "services": ["Custom Solar Solutions", "Off-Grid Systems", "Battery Storage"], "otherServices": ["System Monitoring", "Consulting"], "reviewData": [{"author": "Smallholding Owner", "rating": 5, "comment": "BrightGrid helped us go completely off-grid. The system works perfectly and the support is excellent."}] },
        { "id": "solar-sys-004", "name": "VIP Power Solutions", "location": "Gauteng", "description": "Reliable solar installations with long-term system performance and support.", "rating": 4.7, "reviews": 300, "avatarSeed": "vip-power-solutions-logo", "serviceCategory": "solar-systems", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 35, "services": ["Solar Installations", "Backup Power", "Long-term Support"], "otherServices": ["Financing Options", "Maintenance Contracts"], "reviewData": [{"author": "Gauteng Family", "rating": 5, "comment": "The after-sales support is what sets them apart. They are always available to help."}] },
        { "id": "solar-sys-005", "name": "SunVolt Projects", "location": "Gauteng", "description": "End-to-end solar system design and installation for homes and businesses.", "rating": 4.9, "reviews": 160, "avatarSeed": "sunvolt-projects-logo", "serviceCategory": "solar-systems", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 7, "employees": 18, "services": ["System Design", "Project Management", "Installation"], "otherServices": ["Panel Upgrades", "Battery Replacement"], "reviewData": [{"author": "Architect", "rating": 5, "comment": "Their design and project management are excellent. They work well with other contractors on new builds."}] }
    ],
    "swimming-pool-builders": [
        { "id": "pool-bld-001", "name": "BlueWave Pool Builders", "location": "Gauteng", "description": "Custom swimming pool design and construction for residential properties.", "rating": 4.9, "reviews": 110, "avatarSeed": "bluewave-pool-builders-logo", "serviceCategory": "swimming-pool-builders", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 20, "services": ["Custom Pool Design", "Concrete Pools", "Pool Renovations"], "otherServices": ["Water Features", "Pool Paving"], "reviewData": [{"author": "Sandton Homeowner", "rating": 5, "comment": "They built our dream pool. The process was smooth and the end result is spectacular."}] },
        { "id": "pool-bld-002", "name": "Aqua Pools", "location": "Gauteng", "description": "Professional pool building services including fibreglass and concrete pools.", "rating": 4.8, "reviews": 130, "avatarSeed": "aqua-pools-logo", "serviceCategory": "swimming-pool-builders", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 20, "employees": 25, "services": ["Fibreglass Pools", "Concrete Pools", "Pool Installation"], "otherServices": ["Pool Heating", "Safety Nets"], "reviewData": [{"author": "Pretoria Family", "rating": 5, "comment": "We chose a fibreglass pool and it was installed in just a few days. Very efficient and professional."}] },
        { "id": "pool-bld-003", "name": "Zaza Pool Creations", "location": "Gauteng", "description": "Affordable swimming pool installations with modern finishes and designs.", "rating": 4.7, "reviews": 90, "avatarSeed": "zaza-pool-creations-logo", "serviceCategory": "swimming-pool-builders", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 8, "employees": 12, "services": ["Affordable Pools", "Modern Designs", "Quick Installation"], "otherServices": ["Pool Lighting", "Paving"], "reviewData": [{"author": "First-time Pool Owner", "rating": 5, "comment": "Great value and a beautiful modern design. We are so happy with our new pool."}] },
        { "id": "pool-bld-004", "name": "Ever Clear Pools Gauteng", "location": "Gauteng", "description": "High-quality pool construction tailored to lifestyle and space requirements.", "rating": 4.8, "reviews": 150, "avatarSeed": "ever-clear-pools-gauteng-logo", "serviceCategory": "swimming-pool-builders", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 18, "employees": 22, "services": ["Custom Pool Building", "Lifestyle Pools", "Quality Construction"], "otherServices": ["Pool Covers", "Maintenance Contracts"], "reviewData": [{"author": "Johannesburg Estate", "rating": 5, "comment": "They understood our vision perfectly and built a pool that complements our home and lifestyle."}] },
        { "id": "pool-bld-005", "name": "Stones Pool Projects", "location": "Gauteng", "description": "Turnkey swimming pool solutions from excavation to final handover.", "rating": 4.9, "reviews": 100, "avatarSeed": "stones-pool-projects-logo", "serviceCategory": "swimming-pool-builders", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 16, "services": ["Turnkey Pool Projects", "Excavation", "Construction & Finishing"], "otherServices": ["Landscaping around pool", "Decking"], "reviewData": [{"author": "New Home Builder", "rating": 5, "comment": "They handled everything from start to finish. A truly hassle-free experience."}] }
    ],
    "tar-surfacing": [
        { "id": "tar-001", "name": "SolidRoad Tar Surfacing", "location": "Gauteng", "description": "Professional tar surfacing for driveways, parking areas, and private roads.", "rating": 4.8, "reviews": 140, "avatarSeed": "solidroad-tar-surfacing-logo", "serviceCategory": "tar-surfacing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 15, "employees": 20, "services": ["Tar Driveways", "Asphalt Surfacing", "Road Repairs"], "otherServices": ["Pothole Filling", "Road Markings"], "reviewData": [{"author": "Business Park Manager", "rating": 5, "comment": "They resurfaced our entire parking lot. The quality is excellent and it was done with minimal disruption."}] },
        { "id": "tar-002", "name": "Mzansi TarWorks", "location": "Gauteng", "description": "Affordable tar and asphalt surfacing services across Gauteng.", "rating": 4.7, "reviews": 160, "avatarSeed": "mzansi-tarworks-logo", "serviceCategory": "tar-surfacing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 10, "employees": 18, "services": ["Tar Surfacing", "Asphalt Paving", "Affordable Rates"], "otherServices": ["Driveway Repairs", "Speed Humps"], "reviewData": [{"author": "Homeowner", "rating": 5, "comment": "Very good price for my long driveway. The team worked fast and did a neat job."}] },
        { "id": "tar-003", "name": "PrimePave Surfacing", "location": "Gauteng", "description": "High-quality tar installations designed for durability and smooth finishes.", "rating": 4.9, "reviews": 110, "avatarSeed": "primepave-surfacing-logo", "serviceCategory": "tar-surfacing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 12, "employees": 16, "services": ["Quality Tar Surfacing", "Smooth Finish", "Long-lasting Results"], "otherServices": ["Kerbing", "Stormwater drainage"], "reviewData": [{"author": "Estate Manager", "rating": 5, "comment": "The finish on our new roads is incredibly smooth. A very professional company to work with."}] },
        { "id": "tar-004", "name": "Seal Tar Projects", "location": "Gauteng", "description": "Residential and commercial tar surfacing specialists.", "rating": 4.7, "reviews": 120, "avatarSeed": "seal-tar-projects-logo", "serviceCategory": "tar-surfacing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 9, "employees": 14, "services": ["Tarring Services", "Resurfacing", "Slurry Sealing"], "otherServices": ["Crack Sealing", "Maintenance"], "reviewData": [{"author": "Shopping Centre", "rating": 5, "comment": "They handle all the maintenance for our parking areas, including repairs and resurfacing."}] },
        { "id": "tar-005", "name": "BlackTop Solutions", "location": "Gauteng", "description": "Reliable asphalt surfacing and resurfacing services.", "rating": 4.8, "reviews": 100, "avatarSeed": "blacktop-solutions-logo", "serviceCategory": "tar-surfacing", "isProVerified": true, "isDemo": true, "priorityRank": 99, "yearsInBusiness": 11, "employees": 15, "services": ["Asphalt Paving", "Resurfacing", "Industrial Paving"], "otherServices": ["Pothole Repairs", "Line Marking"], "reviewData": [{"author": "Factory Owner", "rating": 5, "comment": "A very professional team that delivered a high-quality asphalt surface for our loading bay."}] }
    ]
};

export const getProfessionalById = (id: string): Professional | null => {
    for (const category in allProfessionals) {
        if (Object.prototype.hasOwnProperty.call(allProfessionals, category)) {
            const professionalsInCategory = allProfessionals[category];
            const found = professionalsInCategory.find((pro: Professional) => pro.id === id);
            if (found) {
                return found;
            }
        }
    }
    return null;
};
