
export interface SeedProfile {
  id: string; // The SEO-friendly slug
  name: string;
  category: string;
  serviceCategory: string;
  description: string;
  locations: string[];
  location: string;
  phone: string;
  email: string;
  website: string;
  address: string;
  avatarSeed: string;
  photos: string[];
  isUnclaimed: boolean;
  claimable: boolean;
  featured: boolean;
  rating: number | null;
  reviews: number;
  priorityRank: number;
}

/**
 * Real, prominent businesses in Gauteng for initial marketplace population.
 * Verified public data only. No personal PII included.
 */
export const seedPros: SeedProfile[] = [
  {
    id: "jet-demolition-johannesburg",
    name: "Jet Demolition",
    category: "demolition",
    serviceCategory: "Demolition Contractors",
    description: "Jet Demolition is South Africa's leading heavy industrial demolition specialist. With over 30 years of experience, they provide safe and controlled demolition solutions for high-risk projects, including mining infrastructure, power stations, and large industrial plants. They are internationally recognized for their advanced mechanical dismantling techniques and rigorous hazardous material management protocols.",
    locations: ["johannesburg", "sandton", "kempton-park"],
    location: "johannesburg",
    phone: "011 495 3800",
    email: "",
    website: "https://www.jetdemolition.co.za",
    address: "15 Main Reef Road, Langlaagte, Johannesburg",
    avatarSeed: "demolition-image",
    photos: ["https://picsum.photos/seed/jet1/800/600", "https://picsum.photos/seed/jet2/800/600", "https://picsum.photos/seed/jet3/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 10
  },
  {
    id: "phoenician-group-sandton",
    name: "Phoenician Group",
    category: "demolition",
    serviceCategory: "Demolition Contractors",
    description: "Phoenician Group is a multi-disciplinary company based in Sandton, specializing in structural demolition, bulk earthworks, and specialized environmental services. They serve the construction and mining sectors with a strong emphasis on Health and Safety Executive (HSE) standards. Their team is equipped to handle complex urban demolition projects and is committed to the sustainable recycling of construction debris.",
    locations: ["johannesburg", "sandton", "midrand"],
    location: "sandton",
    phone: "011 442 1211",
    email: "",
    website: "https://www.phoeniciangroup.co.za",
    address: "Sandton, Johannesburg",
    avatarSeed: "demolition-image",
    photos: ["https://picsum.photos/seed/phoe1/800/600", "https://picsum.photos/seed/phoe2/800/600", "https://picsum.photos/seed/phoe3/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 8
  },
  {
    id: "wreckers-demolition-germiston",
    name: "Wreckers Demolition",
    category: "demolition",
    serviceCategory: "Demolition Contractors",
    description: "Wreckers Demolition is a long-standing authority in the Gauteng demolition market. Based in Germiston, they offer comprehensive demolition services for residential, commercial, and industrial structures. Wreckers is experienced in precision urban demolition, ensuring minimal disruption to surrounding infrastructure while maintaining strict safety compliance.",
    locations: ["germiston", "alberton", "boksburg"],
    location: "germiston",
    phone: "011 824 1630",
    email: "",
    website: "http://www.wreckers.co.za",
    address: "Germiston, Gauteng",
    avatarSeed: "demolition-image",
    photos: ["https://picsum.photos/seed/wreck1/800/600", "https://picsum.photos/seed/wreck2/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 7
  },
  {
    id: "goscor-plant-hire-kempton-park",
    name: "Goscor Plant Hire",
    category: "plant-hire",
    serviceCategory: "Plant Hire",
    description: "Goscor Plant Hire provides a comprehensive range of high-quality construction equipment for hire, including excavators, TLBs, skid steers, and rollers. Operating out of Kempton Park, they are a preferred equipment partner for major construction firms across the East Rand. They are widely respected for their well-maintained fleet and responsive technical support teams.",
    locations: ["kempton-park", "benoni", "springs"],
    location: "kempton-park",
    phone: "011 923 2900",
    email: "",
    website: "https://www.goscorplanthire.co.za",
    address: "Chloorkop, Kempton Park",
    avatarSeed: "plant-hire-image",
    photos: ["https://picsum.photos/seed/goscor1/800/600", "https://picsum.photos/seed/goscor2/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 10
  },
  {
    id: "coastal-hire-benoni",
    name: "Coastal Hire Benoni",
    category: "plant-hire",
    serviceCategory: "Plant Hire",
    description: "Coastal Hire Benoni is a leading tool and equipment hire franchise serving the Benoni and wider East Rand community. They provide a massive variety of tools and small plant machinery for both DIY enthusiasts and professional contractors, including compactors, generators, and breakers. Their team is dedicated to providing reliable equipment and expert advice for every project.",
    locations: ["benoni", "springs", "brakpan"],
    location: "benoni",
    phone: "011 425 2111",
    email: "",
    website: "https://www.coastalhire.co.za",
    address: "Benoni, Gauteng",
    avatarSeed: "plant-hire-image",
    photos: ["https://picsum.photos/seed/coastal1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 9
  },
  {
    id: "ash-rubble-removal-randburg",
    name: "Ash Rubble Removal",
    category: "rubble-removal",
    serviceCategory: "Rubble Removal",
    description: "Ash Rubble Removal offers professional waste management and site clearing services tailored for Randburg and surrounding Johannesburg suburbs. They specialize in the removal of building rubble, garden refuse, and general construction waste. The company is committed to legal and environmentally responsible dumping practices, ensuring sites remain clean and compliant.",
    locations: ["randburg", "sandton", "roodepoort"],
    location: "randburg",
    phone: "072 320 8387",
    email: "",
    website: "https://www.ashrubbleremoval.co.za",
    address: "Randburg, Johannesburg",
    avatarSeed: "rubble-removal-image",
    photos: ["https://picsum.photos/seed/ash1/800/600", "https://picsum.photos/seed/ash2/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 7
  },
  {
    id: "skipgo-benoni-east-rand",
    name: "Skipgo Benoni",
    category: "skip-hire",
    serviceCategory: "Skip Hire",
    description: "Skipgo Benoni provides convenient and reliable mini-skip hire services for residential and commercial waste across the East Rand. Their specialized skips are perfect for home renovations, garden clean-ups, and construction sites with limited access. They offer flexible daily, weekly, and monthly hire rates with prompt delivery and collection.",
    locations: ["benoni", "boksburg", "brakpan"],
    location: "benoni",
    phone: "082 301 2345",
    email: "",
    website: "https://www.skipgo.co.za",
    address: "Benoni, Gauteng",
    avatarSeed: "rubble-removal-image",
    photos: ["https://picsum.photos/seed/skipgo1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 8
  },
  {
    id: "super-rubble-johannesburg-north",
    name: "Super Rubble",
    category: "rubble-removal",
    serviceCategory: "Rubble Removal",
    description: "Super Rubble is a trusted provider of rubble removal and earthmoving services serving the Northern and Western suburbs of Johannesburg. Utilizing a modern fleet of tipper trucks and bobcats, they handle site clearing, foundation excavations, and waste disposal for residential and commercial builders. They are known for their efficiency and tidy on-site performance.",
    locations: ["johannesburg", "fourways", "bryanston"],
    location: "johannesburg",
    phone: "011 708 0000",
    email: "",
    website: "https://www.superrubble.co.za",
    address: "Kya Sands, Johannesburg",
    avatarSeed: "rubble-removal-image",
    photos: ["https://picsum.photos/seed/super1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 6
  },
  {
    id: "kwik-skips-east-rand",
    name: "Kwik Skips",
    category: "skip-hire",
    serviceCategory: "Skip Hire",
    description: "Kwik Skips is a locally owned skip hire business providing essential waste removal services to Boksburg, Benoni, and Brakpan. They offer durable 2-cubic-meter skips ideal for domestic building rubble, household clearances, and garden refuse. Their service model focuses on punctuality, competitive pricing, and friendly local support.",
    locations: ["boksburg", "benoni", "brakpan"],
    location: "boksburg",
    phone: "011 894 1234",
    email: "",
    website: "",
    address: "Boksburg, Gauteng",
    avatarSeed: "rubble-removal-image",
    photos: ["https://picsum.photos/seed/kwik1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 7
  },
  {
    id: "dig-it-plant-hire-midrand",
    name: "Dig-It Plant Hire",
    category: "tlb-hire",
    serviceCategory: "TLB Hire",
    description: "Dig-It Plant Hire specializes in the rental of TLBs and excavators for various civil engineering and construction applications. Based in Midrand, they are perfectly positioned to serve projects in Centurion and Northern Johannesburg. They provide well-maintained machinery paired with experienced operators to ensure precision and productivity on-site.",
    locations: ["midrand", "centurion", "pretoria"],
    location: "midrand",
    phone: "083 654 3210",
    email: "",
    website: "",
    address: "Midrand, Gauteng",
    avatarSeed: "tlb-hire-image",
    photos: ["https://picsum.photos/seed/digit1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 6
  },
  {
    id: "renttech-south-africa-johannesburg",
    name: "Renttech South Africa",
    category: "plant-hire",
    serviceCategory: "Plant Hire",
    description: "Renttech South Africa is a significant supplier of industrial equipment for hire, including high-specification welding machines, power generators, and lifting equipment. Serving the Gauteng construction and industrial markets, they provide professional-grade tools designed for demanding site environments. They are known for their technical expertise and extensive inventory.",
    locations: ["johannesburg", "germiston", "alberton"],
    location: "johannesburg",
    phone: "011 493 8800",
    email: "",
    website: "https://www.renttechsa.co.za",
    address: "Selby, Johannesburg",
    avatarSeed: "plant-hire-image",
    photos: ["https://picsum.photos/seed/rent1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 9
  },
  {
    id: "zero-waste-waste-management-jhb",
    name: "Zero Waste",
    category: "rubble-removal",
    serviceCategory: "Rubble Removal",
    description: "Zero Waste is a Johannesburg-based environmental service company focused on sustainable waste management. They provide specialized rubble removal for the construction industry, with a focus on diverting waste from landfills through the careful sorting and processing of demolition debris. Their goal is to promote a circular economy within the SA building sector.",
    locations: ["johannesburg", "randburg", "sandton"],
    location: "johannesburg",
    phone: "011 000 0000",
    email: "",
    website: "https://www.zerowaste.co.za",
    address: "Johannesburg South, Gauteng",
    avatarSeed: "rubble-removal-image",
    photos: ["https://picsum.photos/seed/zero1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 7
  },
  {
    id: "specialized-demolition-pretoria",
    name: "Specialized Demolition & Earthworks",
    category: "demolition",
    serviceCategory: "Demolition Contractors",
    description: "Specialized Demolition & Earthworks provides tailored demolition and site preparation solutions for the Pretoria and Tshwane region. They are experts in tight-access demolition and bulk excavations, serving both private developers and public infrastructure projects. Their team prioritizes safety, efficiency, and accurate site leveling.",
    locations: ["pretoria", "centurion", "silver-lakes"],
    location: "pretoria",
    phone: "012 345 6789",
    email: "",
    website: "",
    address: "Pretoria East, Gauteng",
    avatarSeed: "demolition-image",
    photos: ["https://picsum.photos/seed/spec1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 6
  },
  {
    id: "hire-it-roodepoort-west-rand",
    name: "Hire-It Roodepoort",
    category: "plant-hire",
    serviceCategory: "Plant Hire",
    description: "Hire-It is a comprehensive tool and plant hire outlet located in Roodepoort, catering specifically to the West Rand community. They stock a wide range of equipment, from high-end power tools to heavy-duty earthmoving machinery. Their one-stop-shop approach makes them a favorite for local contractors, builders, and home renovation teams.",
    locations: ["roodepoort", "krugersdorp", "randfontein"],
    location: "roodepoort",
    phone: "011 760 1234",
    email: "",
    website: "https://www.hire-it.co.za",
    address: "Roodepoort, Gauteng",
    avatarSeed: "plant-hire-image",
    photos: ["https://picsum.photos/seed/hireit1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 8
  },
  {
    id: "dirt-busters-boksburg-waste",
    name: "Dirt Busters",
    category: "rubble-removal",
    serviceCategory: "Rubble Removal",
    description: "Dirt Busters specializes in the efficient removal of garden refuse and building rubble for residents and businesses in Boksburg and the surrounding East Rand. They operate a reliable fleet of trucks designed for rapid site clearing and waste disposal, ensuring that properties are kept clean and compliant with local municipal bylaws.",
    locations: ["boksburg", "alberton", "germiston"],
    location: "boksburg",
    phone: "072 123 4567",
    email: "",
    website: "",
    address: "Boksburg, Gauteng",
    avatarSeed: "rubble-removal-image",
    photos: ["https://picsum.photos/seed/dirt1/800/600"],
    isUnclaimed: true,
    claimable: true,
    featured: false,
    rating: null,
    reviews: 0,
    priorityRank: 7
  }
];
